// Generates src/words.js for Fiver from the system dictionary.
//
// Run: node tools/make-words.mjs
//
// The output is committed, so the app never depends on this machine's
// dictionaries. Re-run only when changing the filters or the blocklist.
//
// Inputs (Debian: wamerican, cracklib-runtime):
//   /usr/share/dict/american-english   SCOWL-derived, ~104k words
//   /usr/share/dict/cracklib-small     used purely as a "commonness" proxy
//
// Two lists come out:
//   GUESSES  every five-letter word, i.e. what the game will accept as a guess
//   ANSWERS  a common subset, i.e. what it will actually ask you to find
//
// The split matters: accepting only common words makes the game feel broken when
// a real word is rejected, while drawing answers from the full list produces
// miserable puzzles like CALKS or CLIPT.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DICT = '/usr/share/dict/american-english';
const COMMON = '/usr/share/dict/cracklib-small';

// SCOWL's licence requires this notice to travel with any redistribution of the
// word lists or of output derived from them.
const SCOWL_NOTICE = `The word lists below are derived from SCOWL (Spell Checker Oriented Word
 * Lists), by Kevin Atkinson, as shipped in Debian's "wamerican" package.
 *
 *   Copyright 2000-2011 by Kevin Atkinson
 *
 *   Permission to use, copy, modify, distribute and sell these word lists,
 *   the associated scripts, the output created from the scripts, and its
 *   documentation for any purpose is hereby granted without fee, provided
 *   that the above copyright notice appears in all copies and that both that
 *   copyright notice and this permission notice appear in supporting
 *   documentation. Kevin Atkinson makes no representations about the
 *   suitability of this array for any purpose. It is provided "as is"
 *   without express or implied warranty.`;

// Words that pass the filters but make poor answers: too obscure, archaic, or
// regional. Extend this as bad ones surface in play.
const BLOCKLIST = new Set([
  'pewee', 'bosun', 'loamy', 'briar', 'maria', 'hydra', 'liven', 'gismo',
  'calks', 'mavin', 'boink', 'clipt', 'anise', 'coven', 'jells', 'grads',
  'stoke', 'skimp', 'abyss', 'adieu', 'amino', 'sleds', 'wharf', 'pikes',
  'skied', 'piped', 'slang', 'lathe', 'louse', 'macho', 'brash', 'navel',
  'briers', 'aphid', 'bilge', 'cadre', 'demur', 'dross', 'egret', 'fetid',
  'gamut', 'hoary', 'ingot', 'knurl', 'lemur', 'mirth', 'natty', 'offal',
  'pique', 'quire', 'rusks', 'sepia', 'tepid', 'unlit', 'vixen', 'welts',
  'xylem', 'yokel', 'zebus', 'tromp', 'twain', 'unhip', 'vends', 'wonts',
]);

function readWords(path) {
  try {
    return readFileSync(path, 'utf8').split('\n');
  } catch (err) {
    console.error(`Cannot read ${path}: ${err.message}`);
    console.error('On Debian/Ubuntu: sudo apt install wamerican cracklib-runtime');
    process.exit(1);
  }
}

// Test the word as written, without lowercasing first: the dictionary holds
// proper nouns and possessives too, and folding case would let Aaron and Wales
// through as ordinary words.
const fiveLetter = (words) =>
  new Set(words.map((w) => w.trim()).filter((w) => /^[a-z]{5}$/.test(w)));

const guesses = fiveLetter(readWords(DICT));
const common = fiveLetter(readWords(COMMON));

const answers = [...guesses]
  .filter((w) => common.has(w))
  // Plurals and past tenses are legal guesses but tedious answers, and a five
  // letter word ending in S is nearly always the plural of a four letter one.
  .filter((w) => !/(s|ed)$/.test(w))
  .filter((w) => !BLOCKLIST.has(w))
  .sort();

const sortedGuesses = [...guesses].sort();

// Every answer must be an acceptable guess, or the game could refuse its own
// solution. Cheap to assert here rather than discover in play.
const orphans = answers.filter((w) => !guesses.has(w));
if (orphans.length) {
  console.error(`answers missing from guesses: ${orphans.join(', ')}`);
  process.exit(1);
}

const chunk = (words) =>
  words
    .reduce((lines, w, i) => {
      if (i % 10 === 0) lines.push([]);
      lines[lines.length - 1].push(w);
      return lines;
    }, [])
    .map((line) => `  '${line.join(" ")}',`)
    .join('\n');

const out = `// Word lists for Fiver. GENERATED by tools/make-words.mjs -- do not edit by hand.
//
// ANSWERS (${answers.length}) is the pool the game draws puzzles from: common words only.
// GUESSES (${sortedGuesses.length}) is everything it will accept you typing, which is much wider,
// because rejecting a real word feels like a bug even when the word is obscure.
//
// Stored as space-joined strings to keep the file readable and the payload small.
//
/* ${SCOWL_NOTICE}
 */

const ANSWER_DATA = [
${chunk(answers)}
].join(' ');

const GUESS_DATA = [
${chunk(sortedGuesses)}
].join(' ');

/** @type {string[]} common five-letter words, the puzzle pool */
export const ANSWERS = ANSWER_DATA.split(' ');

/** @type {Set<string>} every five-letter word the game accepts as a guess */
export const GUESSES = new Set(GUESS_DATA.split(' '));
`;

const target = join(ROOT, 'src', 'words.js');
writeFileSync(target, out);
console.log(`wrote ${target}`);
console.log(`  answers: ${answers.length}`);
console.log(`  guesses: ${sortedGuesses.length}`);
console.log(`  size:    ${(out.length / 1024).toFixed(1)}KB raw`);
