// Bundled quote pack.
//
// House rules, because they directly affect whether a puzzle is fun:
//   - 40-160 characters. Shorter gives too little signal to deduce from;
//     longer is a slog on a phone screen.
//   - ASCII only. Curly quotes, em-dashes and accents break cell alignment
//     and have no key on the on-screen keyboard.
//   - Stored as written; uppercased at render time.
//
// Add your own by appending to this array. `validateQuotes()` below will warn
// in the console about anything that breaks the rules.

export const QUOTES = [
  // --- Wisdom and philosophy ---
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'I know that I know nothing at all.', author: 'Socrates' },
  { text: 'We are what we repeatedly do. Excellence is a habit.', author: 'Aristotle' },
  { text: 'The whole is greater than the sum of its parts.', author: 'Aristotle' },
  { text: 'Happiness depends upon ourselves.', author: 'Aristotle' },
  { text: 'No man ever steps in the same river twice.', author: 'Heraclitus' },
  { text: 'Waste no more time arguing what a good man should be. Be one.', author: 'Marcus Aurelius' },
  { text: 'You have power over your mind, not outside events.', author: 'Marcus Aurelius' },
  { text: 'The happiness of your life depends upon the quality of your thoughts.', author: 'Marcus Aurelius' },
  { text: 'We suffer more often in imagination than in reality.', author: 'Seneca' },
  { text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca' },
  { text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca' },
  { text: 'It is impossible to learn that which one thinks one already knows.', author: 'Epictetus' },
  { text: 'Wealth consists not in having great possessions but in having few wants.', author: 'Epictetus' },
  { text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'Knowing others is wisdom. Knowing yourself is enlightenment.', author: 'Lao Tzu' },
  { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Real knowledge is to know the extent of one ignorance.', author: 'Confucius' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'Everything has beauty, but not everyone sees it.', author: 'Confucius' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'Three things cannot be long hidden: the sun, the moon, and the truth.', author: 'Buddha' },
  { text: 'Peace comes from within. Do not seek it without.', author: 'Buddha' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'Man is condemned to be free.', author: 'Jean-Paul Sartre' },
  { text: 'Life must be understood backwards, but it must be lived forwards.', author: 'Soren Kierkegaard' },
  { text: 'The limits of my language mean the limits of my world.', author: 'Ludwig Wittgenstein' },
  { text: 'I think, therefore I am.', author: 'Rene Descartes' },
  { text: 'Doubt is the origin of wisdom.', author: 'Rene Descartes' },
  { text: 'Liberty consists in doing what one desires.', author: 'John Stuart Mill' },
  { text: 'The only thing necessary for evil to triumph is for good men to do nothing.', author: 'Edmund Burke' },

  // --- Science, discovery and the mind ---
  { text: 'Imagination is more important than knowledge.', author: 'Albert Einstein' },
  { text: 'Try not to become a man of success, but rather a man of value.', author: 'Albert Einstein' },
  { text: 'The important thing is not to stop questioning.', author: 'Albert Einstein' },
  { text: 'Anyone who has never made a mistake has never tried anything new.', author: 'Albert Einstein' },
  { text: 'Life is like riding a bicycle. To keep your balance you must keep moving.', author: 'Albert Einstein' },
  { text: 'If I have seen further it is by standing on the shoulders of giants.', author: 'Isaac Newton' },
  { text: 'Nothing in life is to be feared, it is only to be understood.', author: 'Marie Curie' },
  { text: 'Be less curious about people and more curious about ideas.', author: 'Marie Curie' },
  { text: 'Somewhere, something incredible is waiting to be known.', author: 'Carl Sagan' },
  { text: 'We are made of star stuff.', author: 'Carl Sagan' },
  { text: 'Extraordinary claims require extraordinary evidence.', author: 'Carl Sagan' },
  { text: 'The first principle is that you must not fool yourself.', author: 'Richard Feynman' },
  { text: 'I would rather have questions that cannot be answered than answers that cannot be questioned.', author: 'Richard Feynman' },
  { text: 'Study hard what interests you the most in the most undisciplined way possible.', author: 'Richard Feynman' },
  { text: 'It is not the strongest of the species that survives, but the most adaptable.', author: 'Charles Darwin' },
  { text: 'A man who dares to waste one hour of time has not discovered the value of life.', author: 'Charles Darwin' },
  { text: 'Science is a way of thinking much more than it is a body of knowledge.', author: 'Carl Sagan' },
  { text: 'Equipped with his five senses, man explores the universe around him.', author: 'Edwin Hubble' },
  { text: 'Look up at the stars and not down at your feet.', author: 'Stephen Hawking' },
  { text: 'Intelligence is the ability to adapt to change.', author: 'Stephen Hawking' },
  { text: 'The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.', author: 'Stephen Hawking' },
  { text: 'What we know is a drop, what we do not know is an ocean.', author: 'Isaac Newton' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'Chance favors the prepared mind.', author: 'Louis Pasteur' },
  { text: 'Nothing has such power to broaden the mind as the ability to investigate.', author: 'Marcus Aurelius' },

  // --- Writers and poets ---
  { text: 'The two most powerful warriors are patience and time.', author: 'Leo Tolstoy' },
  { text: 'Everyone thinks of changing the world, but no one thinks of changing himself.', author: 'Leo Tolstoy' },
  { text: 'It is better to be hated for what you are than loved for what you are not.', author: 'Andre Gide' },
  { text: 'There is no greater agony than bearing an untold story inside you.', author: 'Maya Angelou' },
  { text: 'You may not control all the events that happen to you, but you can decide not to be reduced by them.', author: 'Maya Angelou' },
  { text: 'We write to taste life twice, in the moment and in retrospect.', author: 'Anais Nin' },
  { text: 'We do not see things as they are, we see them as we are.', author: 'Anais Nin' },
  { text: 'A room without books is like a body without a soul.', author: 'Marcus Tullius Cicero' },
  { text: 'The world is a book and those who do not travel read only one page.', author: 'Saint Augustine' },
  { text: 'Not all those who wander are lost.', author: 'J R R Tolkien' },
  { text: 'All we have to decide is what to do with the time that is given us.', author: 'J R R Tolkien' },
  { text: 'It is a truth universally acknowledged that a single man must want a wife.', author: 'Jane Austen' },
  { text: 'There is no charm equal to tenderness of heart.', author: 'Jane Austen' },
  { text: 'It was the best of times, it was the worst of times.', author: 'Charles Dickens' },
  { text: 'No one is useless in this world who lightens the burden of another.', author: 'Charles Dickens' },
  { text: 'The only way out of the labyrinth of suffering is to forgive.', author: 'John Green' },
  { text: 'Beware, for I am fearless, and therefore powerful.', author: 'Mary Shelley' },
  { text: 'I am no bird, and no net ensnares me.', author: 'Charlotte Bronte' },
  { text: 'Whatever our souls are made of, his and mine are the same.', author: 'Emily Bronte' },
  { text: 'Hope is the thing with feathers that perches in the soul.', author: 'Emily Dickinson' },
  { text: 'Tell all the truth but tell it slant.', author: 'Emily Dickinson' },
  { text: 'I took the one less traveled by, and that has made all the difference.', author: 'Robert Frost' },
  { text: 'In three words I can sum up everything I have learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'Do I dare disturb the universe?', author: 'T S Eliot' },
  { text: 'Only those who risk going too far can possibly find out how far one can go.', author: 'T S Eliot' },
  { text: 'The heart wants what it wants, or else it does not care.', author: 'Emily Dickinson' },
  { text: 'And so we beat on, boats against the current.', author: 'F Scott Fitzgerald' },
  { text: 'So we drove on toward death through the cooling twilight.', author: 'F Scott Fitzgerald' },
  { text: 'There is nothing to writing. You just sit at a typewriter and bleed.', author: 'Ernest Hemingway' },
  { text: 'The world breaks everyone, and afterward many are strong at the broken places.', author: 'Ernest Hemingway' },
  { text: 'A man can be destroyed but not defeated.', author: 'Ernest Hemingway' },
  { text: 'It is not down on any map, true places never are.', author: 'Herman Melville' },
  { text: 'I would prefer not to.', author: 'Herman Melville' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'Big Brother is watching you.', author: 'George Orwell' },
  { text: 'If liberty means anything at all, it means the right to tell people what they do not want to hear.', author: 'George Orwell' },
  { text: 'In a time of deceit, telling the truth is a revolutionary act.', author: 'George Orwell' },
  { text: 'It is no measure of health to be well adjusted to a profoundly sick society.', author: 'Jiddu Krishnamurti' },
  { text: 'A word after a word after a word is power.', author: 'Margaret Atwood' },
  { text: 'You never really understand a person until you climb into his skin and walk around in it.', author: 'Harper Lee' },
  { text: 'People generally see what they look for and hear what they listen for.', author: 'Harper Lee' },
  { text: 'It is such a happiness when good people get together.', author: 'Jane Austen' },
  { text: 'The answer, my friend, is blowing in the wind.', author: 'Bob Dylan' },
  { text: 'I dwell in possibility.', author: 'Emily Dickinson' },
  { text: 'Do not go gentle into that good night.', author: 'Dylan Thomas' },
  { text: 'Poetry is what gets lost in translation.', author: 'Robert Frost' },
  { text: 'Wherever they burn books, they will also burn people in the end.', author: 'Heinrich Heine' },

  // --- Mark Twain and the wits ---
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Kindness is the language which the deaf can hear and the blind can see.', author: 'Mark Twain' },
  { text: 'Whenever you find yourself on the side of the majority, it is time to pause.', author: 'Mark Twain' },
  { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
  { text: 'Never let schooling interfere with your education.', author: 'Mark Twain' },
  { text: 'It is easier to fool people than to convince them they have been fooled.', author: 'Mark Twain' },
  { text: 'A lie can travel halfway around the world while the truth is putting on its shoes.', author: 'Mark Twain' },
  { text: 'Age is an issue of mind over matter. If you do not mind, it does not matter.', author: 'Mark Twain' },
  { text: 'Be yourself, everyone else is already taken.', author: 'Oscar Wilde' },
  { text: 'We are all in the gutter, but some of us are looking at the stars.', author: 'Oscar Wilde' },
  { text: 'I can resist everything except temptation.', author: 'Oscar Wilde' },
  { text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde' },
  { text: 'Experience is simply the name we give our mistakes.', author: 'Oscar Wilde' },
  { text: 'The only way to get rid of a temptation is to yield to it.', author: 'Oscar Wilde' },
  { text: 'Always forgive your enemies, nothing annoys them so much.', author: 'Oscar Wilde' },
  { text: 'I have nothing to declare except my genius.', author: 'Oscar Wilde' },
  { text: 'A cynic knows the price of everything and the value of nothing.', author: 'Oscar Wilde' },
  { text: 'The trouble with the world is that the stupid are cocksure and the intelligent full of doubt.', author: 'Bertrand Russell' },
  { text: 'Do not take life too seriously. You will never get out of it alive.', author: 'Elbert Hubbard' },
  { text: 'I have not failed. I have just found ten thousand ways that will not work.', author: 'Thomas Edison' },
  { text: 'Genius is one percent inspiration and ninety nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'Everything you can imagine is real.', author: 'Pablo Picasso' },
  { text: 'Every child is an artist. The problem is staying an artist when you grow up.', author: 'Pablo Picasso' },
  { text: 'Good artists copy, great artists steal.', author: 'Pablo Picasso' },
  { text: 'Wit is educated insolence.', author: 'Aristotle' },
  { text: 'I am so clever that sometimes I do not understand a single word of what I am saying.', author: 'Oscar Wilde' },
  { text: 'The road to success is always under construction.', author: 'Lily Tomlin' },
  { text: 'I always wanted to be somebody, but now I realize I should have been more specific.', author: 'Lily Tomlin' },
  { text: 'A day without laughter is a day wasted.', author: 'Charlie Chaplin' },
  { text: 'Life is a tragedy when seen in close up, but a comedy in long shot.', author: 'Charlie Chaplin' },
  { text: 'Nothing is softer or more flexible than water, yet nothing can resist it.', author: 'Lao Tzu' },
  { text: 'Behind every great fortune there is a crime.', author: 'Honore de Balzac' },
  { text: 'I refuse to join any club that would have me as a member.', author: 'Groucho Marx' },
  { text: 'Outside of a dog, a book is a man best friend.', author: 'Groucho Marx' },
  { text: 'Time flies like an arrow. Fruit flies like a banana.', author: 'Groucho Marx' },
  { text: 'Anyone who lives within their means suffers from a lack of imagination.', author: 'Oscar Wilde' },
  { text: 'Get your facts first, then you can distort them as you please.', author: 'Mark Twain' },
  { text: 'Better to remain silent and be thought a fool than to speak and remove all doubt.', author: 'Mark Twain' },
  { text: 'Clothes make the man. Naked people have little or no influence on society.', author: 'Mark Twain' },

  // --- Leaders, courage and change ---
  { text: 'The only thing we have to fear is fear itself.', author: 'Franklin D Roosevelt' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'Believe you can and you are halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Comparison is the thief of joy.', author: 'Theodore Roosevelt' },
  { text: 'Nothing worth having comes easy.', author: 'Theodore Roosevelt' },
  { text: 'Success is not final, failure is not fatal, it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'If you are going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'Never was so much owed by so many to so few.', author: 'Winston Churchill' },
  { text: 'Attitude is a little thing that makes a big difference.', author: 'Winston Churchill' },
  { text: 'We shall fight on the beaches, we shall never surrender.', author: 'Winston Churchill' },
  { text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'An eye for an eye only ends up making the whole world blind.', author: 'Mahatma Gandhi' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
  { text: 'Darkness cannot drive out darkness, only light can do that.', author: 'Martin Luther King Jr' },
  { text: 'The time is always right to do what is right.', author: 'Martin Luther King Jr' },
  { text: 'Injustice anywhere is a threat to justice everywhere.', author: 'Martin Luther King Jr' },
  { text: 'Our lives begin to end the day we become silent about things that matter.', author: 'Martin Luther King Jr' },
  { text: 'Faith is taking the first step even when you do not see the whole staircase.', author: 'Martin Luther King Jr' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'A winner is a dreamer who never gives up.', author: 'Nelson Mandela' },
  { text: 'The brave man is not he who does not feel afraid, but he who conquers that fear.', author: 'Nelson Mandela' },
  { text: 'No one is born hating another person because of the color of his skin.', author: 'Nelson Mandela' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
  { text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
  { text: 'Great minds discuss ideas, average minds discuss events, small minds discuss people.', author: 'Eleanor Roosevelt' },
  { text: 'Ask not what your country can do for you, ask what you can do for your country.', author: 'John F Kennedy' },
  { text: 'Change is the law of life, and those who look only to the past will miss the future.', author: 'John F Kennedy' },
  { text: 'A rising tide lifts all the boats.', author: 'John F Kennedy' },
  { text: 'Those who dare to fail miserably can achieve greatly.', author: 'Robert F Kennedy' },
  { text: 'Well behaved women seldom make history.', author: 'Laurel Thatcher Ulrich' },
  { text: 'I have learned over the years that when one mind is made up, fear diminishes.', author: 'Rosa Parks' },
  { text: 'You must do the things you think you cannot do.', author: 'Eleanor Roosevelt' },
  { text: 'Freedom is never given, it is won.', author: 'A Philip Randolph' },
  { text: 'We are here not because we are law breakers, we are here in our efforts to become law makers.', author: 'Emmeline Pankhurst' },
  { text: 'I would rather be a rebel than a slave.', author: 'Emmeline Pankhurst' },
  { text: 'None of us is as smart as all of us.', author: 'Ken Blanchard' },

  // --- Work, craft and creativity ---
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { text: 'Innovation distinguishes between a leader and a follower.', author: 'Steve Jobs' },
  { text: 'Design is not just what it looks like. Design is how it works.', author: 'Steve Jobs' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'Art is never finished, only abandoned.', author: 'Leonardo da Vinci' },
  { text: 'Obstacles cannot crush me. Every obstacle yields to stern resolve.', author: 'Leonardo da Vinci' },
  { text: 'I am still learning.', author: 'Michelangelo' },
  { text: 'The greater danger is not that our aim is too high and we miss it, but too low and we reach it.', author: 'Michelangelo' },
  { text: 'Whether you think you can or you think you cannot, you are right.', author: 'Henry Ford' },
  { text: 'Coming together is a beginning, staying together is progress, working together is success.', author: 'Henry Ford' },
  { text: 'Quality means doing it right when no one is looking.', author: 'Henry Ford' },
  { text: 'Failure is simply the opportunity to begin again, more intelligently.', author: 'Henry Ford' },
  { text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Chinese Proverb' },
  { text: 'Perfection is achieved when there is nothing left to take away.', author: 'Antoine de Saint-Exupery' },
  { text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupery' },
  { text: 'If you want to build a ship, teach people to long for the endless sea.', author: 'Antoine de Saint-Exupery' },
  { text: 'It is the time you have spent on your rose that makes your rose so important.', author: 'Antoine de Saint-Exupery' },
  { text: 'What is essential is invisible to the eye.', author: 'Antoine de Saint-Exupery' },
  { text: 'Creativity is intelligence having fun.', author: 'Albert Einstein' },
  { text: 'You cannot use up creativity. The more you use, the more you have.', author: 'Maya Angelou' },
  { text: 'Do not wait for inspiration. It comes while working.', author: 'Henri Matisse' },
  { text: 'Have no fear of perfection, you will never reach it.', author: 'Salvador Dali' },
  { text: 'Every artist was first an amateur.', author: 'Ralph Waldo Emerson' },
  { text: 'Do not go where the path may lead, go instead where there is no path.', author: 'Ralph Waldo Emerson' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'To be yourself in a world constantly trying to make you something else is an achievement.', author: 'Ralph Waldo Emerson' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'Go confidently in the direction of your dreams.', author: 'Henry David Thoreau' },
  { text: 'I went to the woods because I wished to live deliberately.', author: 'Henry David Thoreau' },
  { text: 'The price of anything is the amount of life you exchange for it.', author: 'Henry David Thoreau' },
  { text: 'It is not enough to be busy. The question is, what are we busy about?', author: 'Henry David Thoreau' },
  { text: 'Our life is frittered away by detail. Simplify, simplify.', author: 'Henry David Thoreau' },
  { text: 'Programs must be written for people to read, and only incidentally for machines.', author: 'Harold Abelson' },
  { text: 'Any fool can write code that a computer can understand. Good programmers write code humans understand.', author: 'Martin Fowler' },
  { text: 'Talk is cheap. Show me the code.', author: 'Linus Torvalds' },
  { text: 'First, solve the problem. Then, write the code.', author: 'John Johnson' },
  { text: 'Premature optimization is the root of all evil.', author: 'Donald Knuth' },
  { text: 'Walking on water and developing software from a specification are easy if both are frozen.', author: 'Edward Berard' },
  { text: 'There are only two hard things in computer science: cache invalidation and naming things.', author: 'Phil Karlton' },
  { text: 'Machines take me by surprise with great frequency.', author: 'Alan Turing' },
  { text: 'Those who can imagine anything can create the impossible.', author: 'Alan Turing' },
  { text: 'Sometimes it is the people no one imagines anything of who do the things no one can imagine.', author: 'Alan Turing' },
  { text: 'The most damaging phrase in the language is: we have always done it this way.', author: 'Grace Hopper' },
  { text: 'A ship in port is safe, but that is not what ships are built for.', author: 'Grace Hopper' },

  // --- Persistence, failure and grit ---
  { text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb' },
  { text: 'Success is stumbling from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'It does not matter how many times you fail. You only have to be right once.', author: 'Mark Cuban' },
  { text: 'I have missed more than nine thousand shots in my career. That is why I succeed.', author: 'Michael Jordan' },
  { text: 'You miss one hundred percent of the shots you do not take.', author: 'Wayne Gretzky' },
  { text: 'Hard work beats talent when talent does not work hard.', author: 'Tim Notke' },
  { text: 'The harder I practice, the luckier I get.', author: 'Gary Player' },
  { text: 'It is not the size of the dog in the fight, but the size of the fight in the dog.', author: 'Mark Twain' },
  { text: 'Champions keep playing until they get it right.', author: 'Billie Jean King' },
  { text: 'Pressure is a privilege.', author: 'Billie Jean King' },
  { text: 'Float like a butterfly, sting like a bee.', author: 'Muhammad Ali' },
  { text: 'Do not count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'The fight is won far away from witnesses, behind the lines, in the gym.', author: 'Muhammad Ali' },
  { text: 'It is hard to beat a person who never gives up.', author: 'Babe Ruth' },
  { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
  { text: 'It ain over till it over.', author: 'Yogi Berra' },
  { text: 'When you come to a fork in the road, take it.', author: 'Yogi Berra' },
  { text: 'In theory there is no difference between theory and practice. In practice there is.', author: 'Yogi Berra' },
  { text: 'Nobody goes there anymore, it is too crowded.', author: 'Yogi Berra' },
  { text: 'You cannot cross the sea merely by standing and staring at the water.', author: 'Rabindranath Tagore' },
  { text: 'The bamboo that bends is stronger than the oak that resists.', author: 'Japanese Proverb' },
  { text: 'Smooth seas do not make skillful sailors.', author: 'African Proverb' },
  { text: 'If you want to go fast, go alone. If you want to go far, go together.', author: 'African Proverb' },
  { text: 'A river cuts through rock not because of its power but its persistence.', author: 'Jim Watkins' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius' },
  { text: 'Rock bottom became the solid foundation on which I rebuilt my life.', author: 'J K Rowling' },
  { text: 'It is our choices that show what we truly are, far more than our abilities.', author: 'J K Rowling' },
  { text: 'Happiness can be found even in the darkest of times if one remembers to turn on the light.', author: 'J K Rowling' },
  { text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
  { text: 'Everything is hard before it is easy.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Whatever you can do or dream you can, begin it. Boldness has genius in it.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Knowing is not enough, we must apply. Willing is not enough, we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein' },

  // --- Curious facts and history ---
  { text: 'Honey never spoils. Jars found in ancient tombs are still edible today.', author: 'Fact' },
  { text: 'Octopuses have three hearts and blue blood.', author: 'Fact' },
  { text: 'A group of flamingos is called a flamboyance.', author: 'Fact' },
  { text: 'Bananas are berries, but strawberries are not.', author: 'Fact' },
  { text: 'The shortest war in history lasted only thirty eight minutes.', author: 'Fact' },
  { text: 'Sharks existed before trees did.', author: 'Fact' },
  { text: 'A day on Venus is longer than a year on Venus.', author: 'Fact' },
  { text: 'The human nose can detect over one trillion distinct scents.', author: 'Fact' },
  { text: 'Wombat droppings are cube shaped.', author: 'Fact' },
  { text: 'The Eiffel Tower can grow six inches taller during the summer.', author: 'Fact' },
  { text: 'Cleopatra lived closer in time to the moon landing than to the pyramids.', author: 'Fact' },
  { text: 'There are more possible chess games than atoms in the observable universe.', author: 'Fact' },
  { text: 'Sea otters hold hands while sleeping so they do not drift apart.', author: 'Fact' },
  { text: 'The dot over a lowercase letter i is called a tittle.', author: 'Fact' },
  { text: 'Scotland national animal is the unicorn.', author: 'Fact' },
  { text: 'A bolt of lightning is five times hotter than the surface of the sun.', author: 'Fact' },
  { text: 'Butterflies taste with their feet.', author: 'Fact' },
  { text: 'The first computer programmer was a woman named Ada Lovelace.', author: 'Fact' },
  { text: 'Oxford University is older than the Aztec Empire.', author: 'Fact' },
  { text: 'A single strand of spider silk is stronger than steel of the same width.', author: 'Fact' },
  { text: 'Hot water can freeze faster than cold water under the right conditions.', author: 'Fact' },
  { text: 'Cows have best friends and get stressed when they are separated.', author: 'Fact' },
  { text: 'The moon is slowly drifting away from Earth every single year.', author: 'Fact' },
  { text: 'Penguins propose to their mates with a carefully chosen pebble.', author: 'Fact' },
  { text: 'Bubble wrap was originally invented as textured wallpaper.', author: 'Fact' },
  { text: 'The inventor of the frisbee was turned into a frisbee after he died.', author: 'Fact' },
  { text: 'There is enough gold in the earth core to coat the planet knee deep.', author: 'Fact' },
  { text: 'A jiffy is an actual unit of time equal to one hundredth of a second.', author: 'Fact' },
  { text: 'Humans share about sixty percent of their DNA with bananas.', author: 'Fact' },
  { text: 'The longest word without a vowel other than y is rhythms.', author: 'Fact' },
  { text: 'Polar bears have black skin under their translucent fur.', author: 'Fact' },
  { text: 'Snails can sleep for up to three years at a time.', author: 'Fact' },
  { text: 'The unicorn was declared the national animal of Scotland in the twelfth century.', author: 'Fact' },
  { text: 'Tomatoes were once believed to be poisonous by wealthy Europeans.', author: 'Fact' },
  { text: 'An ostrich eye is bigger than its brain.', author: 'Fact' },

  // --- Proverbs and sayings ---
  { text: 'The early bird catches the worm, but the second mouse gets the cheese.', author: 'Proverb' },
  { text: 'A smooth sea never made a skilled sailor.', author: 'Proverb' },
  { text: 'Do not judge a book by its cover.', author: 'Proverb' },
  { text: 'Actions speak louder than words.', author: 'Proverb' },
  { text: 'When the wind of change blows, some build walls and others build windmills.', author: 'Chinese Proverb' },
  { text: 'A gem cannot be polished without friction.', author: 'Chinese Proverb' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'By failing to prepare, you are preparing to fail.', author: 'Benjamin Franklin' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'Either write something worth reading or do something worth writing.', author: 'Benjamin Franklin' },
  { text: 'Lost time is never found again.', author: 'Benjamin Franklin' },
  { text: 'He that can have patience can have what he will.', author: 'Benjamin Franklin' },
  { text: 'Speak softly and carry a big stick.', author: 'African Proverb' },
  { text: 'It takes a village to raise a child.', author: 'African Proverb' },
  { text: 'However long the night, the dawn will break.', author: 'African Proverb' },
  { text: 'The axe forgets, but the tree remembers.', author: 'African Proverb' },
  { text: 'Rain does not fall on one roof alone.', author: 'African Proverb' },
  { text: 'A single bracelet does not jingle.', author: 'African Proverb' },
  { text: 'Smooth roads never make good drivers.', author: 'Proverb' },
  { text: 'The nail that sticks out gets hammered down.', author: 'Japanese Proverb' },
  { text: 'Vision without action is a daydream. Action without vision is a nightmare.', author: 'Japanese Proverb' },
  { text: 'One kind word can warm three winter months.', author: 'Japanese Proverb' },
  { text: 'If you are patient in one moment of anger, you will escape a hundred days of sorrow.', author: 'Chinese Proverb' },
  { text: 'Better to light a candle than to curse the darkness.', author: 'Chinese Proverb' },
  { text: 'Teachers open the door, but you must enter by yourself.', author: 'Chinese Proverb' },
  { text: 'A book is a garden carried in the pocket.', author: 'Arabian Proverb' },
  { text: 'Ask about your neighbors before you buy the house.', author: 'Jewish Proverb' },
  { text: 'Do not be so humble, you are not that great.', author: 'Golda Meir' },
  { text: 'Trust in God, but tie your camel.', author: 'Arabian Proverb' },
  { text: 'What is done cannot be undone.', author: 'Proverb' },
  { text: 'Necessity is the mother of invention.', author: 'Proverb' },
  { text: 'Still waters run deep.', author: 'Proverb' },
  { text: 'A watched pot never boils.', author: 'Proverb' },
  { text: 'Do not put all your eggs in one basket.', author: 'Proverb' },

  // --- Music, film and the modern age ---
  { text: 'Without music, life would be a mistake.', author: 'Friedrich Nietzsche' },
  { text: 'Where words fail, music speaks.', author: 'Hans Christian Andersen' },
  { text: 'Music is the universal language of mankind.', author: 'Henry Wadsworth Longfellow' },
  { text: 'Life is what happens when you are busy making other plans.', author: 'John Lennon' },
  { text: 'You may say I am a dreamer, but I am not the only one.', author: 'John Lennon' },
  { text: 'And in the end, the love you take is equal to the love you make.', author: 'Paul McCartney' },
  { text: 'I get by with a little help from my friends.', author: 'The Beatles' },
  { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates' },
  { text: 'May the Force be with you.', author: 'Star Wars' },
  { text: 'Do or do not. There is no try.', author: 'Yoda' },
  { text: 'Fear is the path to the dark side.', author: 'Yoda' },
  { text: 'Frankly my dear, I do not give a damn.', author: 'Gone with the Wind' },
  { text: 'Here is looking at you, kid.', author: 'Casablanca' },
  { text: 'Toto, I have a feeling we are not in Kansas anymore.', author: 'The Wizard of Oz' },
  { text: 'Life is like a box of chocolates. You never know what you are going to get.', author: 'Forrest Gump' },
  { text: 'To infinity and beyond.', author: 'Buzz Lightyear' },
  { text: 'When life gets you down, you know what you got to do? Just keep swimming.', author: 'Finding Nemo' },
  { text: 'Hakuna matata means no worries for the rest of your days.', author: 'The Lion King' },
  { text: 'With great power comes great responsibility.', author: 'Spider-Man' },
  { text: 'You either die a hero or you live long enough to see yourself become the villain.', author: 'The Dark Knight' },
  { text: 'Houston, we have a problem.', author: 'Apollo 13' },
  { text: 'That is one small step for man, one giant leap for mankind.', author: 'Neil Armstrong' },
  { text: 'We choose to go to the moon not because it is easy, but because it is hard.', author: 'John F Kennedy' },
  { text: 'The truth is out there.', author: 'The X-Files' },
  { text: 'A mind needs books as a sword needs a whetstone, if it is to keep its edge.', author: 'Game of Thrones' },
  { text: 'I am going to make him an offer he cannot refuse.', author: 'The Godfather' },
  { text: 'Elementary, my dear Watson.', author: 'Sherlock Holmes' },
  { text: 'When you have eliminated the impossible, whatever remains must be the truth.', author: 'Sherlock Holmes' },
  { text: 'You see, but you do not observe.', author: 'Sherlock Holmes' },
  { text: 'It is a capital mistake to theorize before one has data.', author: 'Sherlock Holmes' },

  // --- Longer passages, for the hard tier ---
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'Success is not how high you have climbed, but how you make a positive difference to the world.', author: 'Roy T Bennett' },
  { text: 'Twenty years from now you will be more disappointed by the things you did not do than by the ones you did.', author: 'Mark Twain' },
  { text: 'The pessimist complains about the wind, the optimist expects it to change, the realist adjusts the sails.', author: 'William Arthur Ward' },
  { text: 'Courage is not the absence of fear, but rather the judgment that something else is more important than fear.', author: 'Ambrose Redmoon' },
  { text: 'A person who never made a mistake never tried anything new, and a life without error is a life without risk.', author: 'Anonymous' },
  { text: 'Education is not the filling of a pail, but the lighting of a fire that burns for the rest of a lifetime.', author: 'William Butler Yeats' },
  { text: 'The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', author: 'Isaac Asimov' },
  { text: 'Your assumptions are your windows on the world. Scrub them off every once in a while or the light will not come in.', author: 'Isaac Asimov' },
  { text: 'People will forget what you said, people will forget what you did, but they will never forget how you made them feel.', author: 'Maya Angelou' },
  { text: 'If you want to know what a man is like, take a good look at how he treats his inferiors, not his equals.', author: 'J K Rowling' },
  { text: 'It is not our abilities that show what we truly are, it is the choices we make when no one is watching us.', author: 'Anonymous' },
  { text: 'Somewhere something incredible is waiting to be known, and the universe is under no obligation to make sense to you.', author: 'Carl Sagan' },
  { text: 'The cure for boredom is curiosity, and there is no known cure for curiosity once it has taken proper hold of you.', author: 'Dorothy Parker' },
  { text: 'Do not judge each day by the harvest you reap, but rather by the seeds that you plant along the way.', author: 'Robert Louis Stevenson' },
  { text: 'Never doubt that a small group of thoughtful citizens can change the world, indeed it is the only thing that ever has.', author: 'Margaret Mead' },
  { text: 'The difference between a successful person and others is not a lack of strength but rather a lack of will.', author: 'Vince Lombardi' },
  { text: 'Perfection is not attainable, but if we chase perfection we can catch excellence somewhere along the way.', author: 'Vince Lombardi' },
  { text: 'We are all faced with a series of great opportunities brilliantly disguised as impossible situations.', author: 'Chuck Swindoll' },
  { text: 'Everybody is a genius, but if you judge a fish by its ability to climb a tree it will live believing it is stupid.', author: 'Albert Einstein' },
  { text: 'The greatest weapon against stress is our ability to choose one thought over another and hold it there.', author: 'William James' },
  { text: 'Act as if what you do makes a difference, because in ways you may never fully measure, it absolutely does.', author: 'William James' },
  { text: 'Happiness is not something ready made. It comes from your own actions and the way you meet each ordinary day.', author: 'Dalai Lama' },
  { text: 'Remember that sometimes not getting what you want is a wonderful and quite unexpected stroke of good luck.', author: 'Dalai Lama' },
  { text: 'In the end, we will remember not the words of our enemies, but the silence of our friends who said nothing.', author: 'Martin Luther King Jr' },
  { text: 'The measure of intelligence is the ability to change, and the measure of wisdom is knowing when you should.', author: 'Anonymous' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them in the first place.', author: 'Albert Einstein' },
  { text: 'A good traveler has no fixed plans and is not intent on arriving at any particular place at all.', author: 'Lao Tzu' },
  { text: 'To handle yourself use your head, but whenever you must handle other people be sure to use your heart.', author: 'Eleanor Roosevelt' },
  { text: 'The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.', author: 'Helen Keller' },
  { text: 'Optimism is the faith that leads to achievement, for nothing can be done without hope and confidence.', author: 'Helen Keller' },
  { text: 'Alone we can do so little, together we can do so much, and no worthwhile thing is ever built by one pair of hands.', author: 'Helen Keller' },
  { text: 'Keep your face always toward the sunshine and the shadows will fall away somewhere behind you.', author: 'Walt Whitman' },
  { text: 'Be curious, not judgmental, because every person you meet is fighting a battle you know nothing about.', author: 'Anonymous' },
  { text: 'The two hardest things to say in life are hello for the first time and goodbye for the last.', author: 'Moira Rogers' },

  // --- More science, mathematics and engineering ---
  { text: 'I was taught that the way of progress was neither swift nor easy.', author: 'Marie Curie' },
  { text: 'A scientist in a laboratory is not a mere technician, but a child confronting natural phenomena.', author: 'Marie Curie' },
  { text: 'Measure what is measurable, and make measurable what is not so.', author: 'Galileo Galilei' },
  { text: 'All truths are easy to understand once they are discovered. The point is to discover them.', author: 'Galileo Galilei' },
  { text: 'The book of nature is written in the language of mathematics.', author: 'Galileo Galilei' },
  { text: 'Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.', author: 'Isaac Newton' },
  { text: 'Nature is pleased with simplicity, and nature is no dummy.', author: 'Isaac Newton' },
  { text: 'We are made of star stuff, and we are a way for the cosmos to know itself.', author: 'Carl Sagan' },
  { text: 'Imagination will often carry us to worlds that never were, but without it we go nowhere.', author: 'Carl Sagan' },
  { text: 'The universe is not only stranger than we imagine, it is stranger than we can imagine.', author: 'J B S Haldane' },
  { text: 'The good thing about science is that it is true whether or not you believe in it.', author: 'Neil deGrasse Tyson' },
  { text: 'The most exciting phrase to hear in science is not eureka, but that is funny.', author: 'Isaac Asimov' },
  { text: 'Research is what I am doing when I do not know what I am doing.', author: 'Wernher von Braun' },
  { text: 'An expert is a person who has made all the mistakes that can be made in a very narrow field.', author: 'Niels Bohr' },
  { text: 'Prediction is very difficult, especially about the future.', author: 'Niels Bohr' },
  { text: 'If quantum mechanics has not profoundly shocked you, then you have not understood it yet.', author: 'Niels Bohr' },
  { text: 'The first principle is that you must not fool yourself, and you are the easiest person to fool.', author: 'Richard Feynman' },
  { text: 'Nature uses only the longest threads to weave her patterns.', author: 'Richard Feynman' },
  { text: 'What I cannot create, I do not understand.', author: 'Richard Feynman' },
  { text: 'Study hard what interests you the most, in the most undisciplined and original manner possible.', author: 'Richard Feynman' },
  { text: 'Pure mathematics is, in its way, the poetry of logical ideas.', author: 'Albert Einstein' },
  { text: 'The essence of mathematics lies in its freedom.', author: 'Georg Cantor' },
  { text: 'Mathematics is the art of giving the same name to different things.', author: 'Henri Poincare' },
  { text: 'It is by logic that we prove, but by intuition that we discover.', author: 'Henri Poincare' },
  { text: 'There is no royal road to geometry.', author: 'Euclid' },
  { text: 'Give me a place to stand and I will move the earth.', author: 'Archimedes' },
  { text: 'Mathematics is not about numbers or equations, it is about understanding.', author: 'William Thurston' },
  { text: 'Obstacles cannot crush me, for every obstacle yields to stern resolve.', author: 'Leonardo da Vinci' },
  { text: 'Nature never breaks her own laws.', author: 'Leonardo da Vinci' },
  { text: 'Any sufficiently advanced technology is indistinguishable from magic.', author: 'Arthur C Clarke' },
  { text: 'The only way of discovering the limits of the possible is to go beyond them into the impossible.', author: 'Arthur C Clarke' },
  { text: 'The machine does not isolate us from the great problems of nature but plunges us more deeply into them.', author: 'Antoine de Saint Exupery' },
  { text: 'Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.', author: 'Antoine de Saint Exupery' },
  { text: 'It is not the strongest of the species that survives, but the one most adaptable to change.', author: 'Leon Megginson' },
  { text: 'Somewhere in the world there is an equation that explains what you are afraid to ask.', author: 'Anonymous' },
  { text: 'Errors using inadequate data are much less than those using no data at all.', author: 'Charles Babbage' },
  { text: 'The question of whether a machine can think is no more interesting than whether a submarine can swim.', author: 'Edsger Dijkstra' },
  { text: 'Simplicity is a great virtue but it requires hard work to achieve it, and education to appreciate it.', author: 'Edsger Dijkstra' },
  { text: 'Testing shows the presence, not the absence of bugs.', author: 'Edsger Dijkstra' },
  { text: 'The purpose of computing is insight, not numbers.', author: 'Richard Hamming' },
  { text: 'In science, if you know what you are doing, you should not be doing it.', author: 'Richard Hamming' },
  { text: 'Programs must be written for people to read, and only incidentally for machines to execute.', author: 'Harold Abelson' },
  { text: 'Controlling complexity is the essence of computer programming.', author: 'Brian Kernighan' },
  { text: 'Everything should be made as simple as possible, but not simpler.', author: 'Albert Einstein' },
  { text: 'A theory that explains everything explains nothing at all.', author: 'Karl Popper' },
  { text: 'Good tests kill flawed theories, and we remain alive to guess again.', author: 'Karl Popper' },
  { text: 'Science must begin with myths, and with the criticism of myths.', author: 'Karl Popper' },
  { text: 'The map is not the territory, and the menu is not the meal.', author: 'Alfred Korzybski' },
  { text: 'All models are wrong, but some of them are useful.', author: 'George Box' },
  { text: 'A discovery is said to be an accident meeting a prepared mind.', author: 'Albert Szent Gyorgyi' },
  { text: 'Chance favours only the prepared mind.', author: 'Louis Pasteur' },
  { text: 'Science knows no country, because knowledge belongs to humanity and is the torch which illuminates the world.', author: 'Louis Pasteur' },
  { text: 'Let me tell you the secret that has led me to my goal: my strength lies solely in my tenacity.', author: 'Louis Pasteur' },

  // --- Nature, the sea and the sky ---
  { text: 'Look deep into nature, and then you will understand everything better.', author: 'Albert Einstein' },
  { text: 'In every walk with nature one receives far more than he seeks.', author: 'John Muir' },
  { text: 'The mountains are calling and I must go.', author: 'John Muir' },
  { text: 'When one tugs at a single thing in nature, he finds it attached to the rest of the world.', author: 'John Muir' },
  { text: 'The clearest way into the universe is through a forest wilderness.', author: 'John Muir' },
  { text: 'Adopt the pace of nature: her secret is patience.', author: 'Ralph Waldo Emerson' },
  { text: 'The earth laughs in flowers.', author: 'Ralph Waldo Emerson' },
  { text: 'Live in the sunshine, swim the sea, drink the wild air.', author: 'Ralph Waldo Emerson' },
  { text: 'The sea, once it casts its spell, holds one in its net of wonder forever.', author: 'Jacques Cousteau' },
  { text: 'The water is the driver of nature.', author: 'Leonardo da Vinci' },
  { text: 'A river cuts through rock not because of its power but because of its persistence.', author: 'Jim Watkins' },
  { text: 'Rivers know this: there is no hurry, we shall get there some day.', author: 'A A Milne' },
  { text: 'Nature does not need us. We need nature.', author: 'Anonymous' },
  { text: 'To see a world in a grain of sand, and heaven in a wild flower.', author: 'William Blake' },
  { text: 'The sky is the daily bread of the eyes.', author: 'Ralph Waldo Emerson' },
  { text: 'For my part I know nothing with any certainty, but the sight of the stars makes me dream.', author: 'Vincent van Gogh' },
  { text: 'The stars are the land marks of the universe.', author: 'John Herschel' },
  { text: 'Two things fill the mind with wonder: the starry heavens above and the moral law within.', author: 'Immanuel Kant' },
  { text: 'The desert is a natural extension of the inner silence of the body.', author: 'Jean Baudrillard' },
  { text: 'A tree is our most intimate contact with nature.', author: 'George Nakashima' },
  { text: 'Trees are poems that the earth writes upon the sky.', author: 'Kahlil Gibran' },
  { text: 'In the depth of winter I finally learned that there was in me an invincible summer.', author: 'Albert Camus' },
  { text: 'Autumn is a second spring when every leaf is a flower.', author: 'Albert Camus' },
  { text: 'Storms make trees take deeper roots.', author: 'Dolly Parton' },
  { text: 'No winter lasts forever, no spring skips its turn.', author: 'Hal Borland' },
  { text: 'Wilderness is not a luxury but a necessity of the human spirit.', author: 'Edward Abbey' },
  { text: 'The mountain remains unmoved at seeming defeat by the mist.', author: 'Rabindranath Tagore' },
  { text: 'Clouds come floating into my life, no longer to carry rain or usher storm, but to add colour to my sunset sky.', author: 'Rabindranath Tagore' },
  { text: 'Let us leave a little fruit for the birds.', author: 'Anonymous' },
  { text: 'The moon is a friend for the lonesome to talk to.', author: 'Carl Sandburg' },
  { text: 'Nothing is so beautiful as spring, when weeds in wheels shoot long and lovely and lush.', author: 'Gerard Manley Hopkins' },
  { text: 'Earth and sky, woods and fields, lakes and rivers, the mountain and the sea, are excellent schoolmasters.', author: 'John Lubbock' },

  // --- Books, reading and language ---
  { text: 'A book is a dream that you hold in your hand.', author: 'Neil Gaiman' },
  { text: 'Books are a uniquely portable magic.', author: 'Stephen King' },
  { text: 'If you do not have time to read, you do not have the time or the tools to write.', author: 'Stephen King' },
  { text: 'The road to hell is paved with adverbs.', author: 'Stephen King' },
  { text: 'Read a thousand books and your words will flow like a river.', author: 'Lisa See' },
  { text: 'There is no friend as loyal as a book.', author: 'Ernest Hemingway' },
  { text: 'Write drunk, edit sober is bad advice. Write badly, then fix it, is much better.', author: 'Anonymous' },
  { text: 'The first draft of anything is rubbish, and knowing that is what lets you finish it.', author: 'Anonymous' },
  { text: 'Easy reading is damned hard writing.', author: 'Nathaniel Hawthorne' },
  { text: 'Substitute damn every time you write very, and your writing will improve.', author: 'Mark Twain' },
  { text: 'The difference between the right word and the almost right word is the difference between lightning and a bug.', author: 'Mark Twain' },
  { text: 'Writing is easy: all you have to do is cross out the wrong words.', author: 'Mark Twain' },
  { text: 'I have only made this letter longer because I have not had the time to make it shorter.', author: 'Blaise Pascal' },
  { text: 'Vigorous writing is concise. A sentence should contain no unnecessary words.', author: 'William Strunk Jr' },
  { text: 'Omit needless words.', author: 'William Strunk Jr' },
  { text: 'Never use a long word where a short one will do.', author: 'George Orwell' },
  { text: 'If thought corrupts language, language can also corrupt thought.', author: 'George Orwell' },
  { text: 'Good prose is like a window pane.', author: 'George Orwell' },
  { text: 'Whereof one cannot speak, thereof one must be silent.', author: 'Ludwig Wittgenstein' },
  { text: 'Language is a city to the building of which every human being brought a stone.', author: 'Ralph Waldo Emerson' },
  { text: 'A different language is a different vision of life.', author: 'Federico Fellini' },
  { text: 'One language sets you in a corridor for life. Two languages open every door along the way.', author: 'Frank Smith' },
  { text: 'To have another language is to possess a second soul.', author: 'Charlemagne' },
  { text: 'Words are, of course, the most powerful drug used by mankind.', author: 'Rudyard Kipling' },
  { text: 'The pen is mightier than the sword.', author: 'Edward Bulwer Lytton' },
  { text: 'I cannot live without books.', author: 'Thomas Jefferson' },
  { text: 'Reading is to the mind what exercise is to the body.', author: 'Joseph Addison' },
  { text: 'There is no substitute for books in the life of a child.', author: 'Mary Ellen Chase' },
  { text: 'A great book should leave you with many experiences and slightly exhausted at the end.', author: 'William Styron' },
  { text: 'Never trust anyone who has not brought a book with them.', author: 'Lemony Snicket' },
  { text: 'The person who does not read good books has no advantage over the person who cannot read them.', author: 'Mark Twain' },
  { text: 'Libraries were full of ideas, perhaps the most dangerous and powerful of all weapons.', author: 'Sarah J Maas' },
  { text: 'A library is not a luxury but one of the necessities of life.', author: 'Henry Ward Beecher' },
  { text: 'When I have a little money, I buy books, and if any is left I buy food and clothes.', author: 'Erasmus' },
  { text: 'Poetry is when an emotion has found its thought and the thought has found words.', author: 'Robert Frost' },
  { text: 'No tears in the writer, no tears in the reader. No surprise for the writer, no surprise for the reader.', author: 'Robert Frost' },
  { text: 'Writing a poem is discovering.', author: 'Robert Frost' },

  // --- Music and the arts ---
  { text: 'Music is the shorthand of emotion.', author: 'Leo Tolstoy' },
  { text: 'Music is the strongest form of magic.', author: 'Marilyn Manson' },
  { text: 'The only truth is music.', author: 'Jack Kerouac' },
  { text: 'Music is the divine way to tell beautiful, poetic things to the heart.', author: 'Pablo Casals' },
  { text: 'To play a wrong note is insignificant. To play without passion is inexcusable.', author: 'Ludwig van Beethoven' },
  { text: 'Music is a higher revelation than all wisdom and philosophy.', author: 'Ludwig van Beethoven' },
  { text: 'Music should strike fire from the heart of man, and bring tears from the eyes of woman.', author: 'Ludwig van Beethoven' },
  { text: 'The notes I handle no better than many pianists, but the pauses between the notes are where the art resides.', author: 'Artur Schnabel' },
  { text: 'Silence is the canvas that music is painted on.', author: 'Anonymous' },
  { text: 'It is not enough to play what is written. You must play what is not written.', author: 'Anonymous' },
  { text: 'Talking about music is like dancing about architecture.', author: 'Martin Mull' },
  { text: 'A painting is never finished, it simply stops in interesting places.', author: 'Paul Gardner' },
  { text: 'Art is not what you see, but what you make others see.', author: 'Edgar Degas' },
  { text: 'Creativity takes courage.', author: 'Henri Matisse' },
  { text: 'I do not paint things, I paint only the differences between things.', author: 'Henri Matisse' },
  { text: 'Colour is my daily obsession, joy and torment.', author: 'Claude Monet' },
  { text: 'I must have flowers, always and always.', author: 'Claude Monet' },
  { text: 'Learn the rules like a professional so you can break them like an artist.', author: 'Pablo Picasso' },
  { text: 'Art washes away from the soul the dust of everyday life.', author: 'Pablo Picasso' },
  { text: 'I dream my painting and then I paint my dream.', author: 'Vincent van Gogh' },
  { text: 'Great things are not done by impulse, but by a series of small things brought together.', author: 'Vincent van Gogh' },
  { text: 'If you hear a voice within you saying you cannot paint, then by all means paint, and that voice will be silenced.', author: 'Vincent van Gogh' },
  { text: 'The chief enemy of creativity is good taste.', author: 'Pablo Picasso' },
  { text: 'Every child is an artist. The problem is how to remain an artist once we grow up.', author: 'Pablo Picasso' },
  { text: 'Sculpture is the art of the intelligence.', author: 'Pablo Picasso' },
  { text: 'I saw the angel in the marble and carved until I set him free.', author: 'Michelangelo' },
  { text: 'The greater danger for most of us lies not in setting our aim too high but in settling for too little.', author: 'Michelangelo' },
  { text: 'Photography is the story I fail to put into words.', author: 'Destin Sparks' },
  { text: 'You do not take a photograph, you make it.', author: 'Ansel Adams' },
  { text: 'There are no rules for good photographs, there are only good photographs.', author: 'Ansel Adams' },

  // --- Sport, the body and the will ---
  { text: 'You miss one hundred percent of the shots you never take.', author: 'Wayne Gretzky' },
  { text: 'I skate to where the puck is going to be, not where it has been.', author: 'Wayne Gretzky' },
  { text: 'I have failed over and over again in my life, and that is precisely why I succeed.', author: 'Michael Jordan' },
  { text: 'Some people want it to happen, some wish it would happen, others make it happen.', author: 'Michael Jordan' },
  { text: 'Talent wins games, but teamwork and intelligence win championships.', author: 'Michael Jordan' },
  { text: 'It is not the will to win that matters, everyone has that. It is the will to prepare to win that matters.', author: 'Paul Bryant' },
  { text: 'I hated every minute of training, but I said, do not quit. Suffer now and live the rest of your life as a champion.', author: 'Muhammad Ali' },
  { text: 'The fight is won or lost far away from witnesses, behind the lines, in the gym, out there on the road.', author: 'Muhammad Ali' },
  { text: 'Age is whatever you think it is. You are as old as you think you are.', author: 'Muhammad Ali' },
  { text: 'It is not the size of a man but the size of his heart that matters.', author: 'Evander Holyfield' },
  { text: 'Do not practise until you get it right. Practise until you cannot get it wrong.', author: 'Anonymous' },
  { text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon' },
  { text: 'Sport has the power to change the world. It has the power to inspire and to unite people in a way that little else does.', author: 'Nelson Mandela' },
  { text: 'The body achieves what the mind believes.', author: 'Anonymous' },
  { text: 'Take care of your body. It is the only place you have to live.', author: 'Jim Rohn' },
  { text: 'Walking is the best possible exercise. Habituate yourself to walk very far.', author: 'Thomas Jefferson' },
  { text: 'An early morning walk is a blessing for the whole day.', author: 'Henry David Thoreau' },
  { text: 'All truly great thoughts are conceived while walking.', author: 'Friedrich Nietzsche' },
  { text: 'If you are in a bad mood, go for a walk. If you are still in a bad mood, go for another walk.', author: 'Hippocrates' },
  { text: 'Walking is a man best medicine.', author: 'Hippocrates' },
  { text: 'Fatigue makes cowards of us all.', author: 'Vince Lombardi' },
  { text: 'It is not whether you get knocked down, it is whether you get up.', author: 'Vince Lombardi' },
  { text: 'Run when you can, walk if you have to, crawl if you must, just never give up.', author: 'Dean Karnazes' },
  { text: 'The miracle is not that I finished, the miracle is that I had the courage to start.', author: 'John Bingham' },
  { text: 'Pain is temporary, quitting lasts forever.', author: 'Lance Armstrong' },

  // --- Building, design and craft ---
  { text: 'Form follows function.', author: 'Louis Sullivan' },
  { text: 'God is in the details.', author: 'Ludwig Mies van der Rohe' },
  { text: 'Architecture starts when you carefully put two bricks together. There it begins.', author: 'Ludwig Mies van der Rohe' },
  { text: 'A doctor can bury his mistakes, but an architect can only advise his client to plant vines.', author: 'Frank Lloyd Wright' },
  { text: 'Study nature, love nature, stay close to nature. It will never fail you.', author: 'Frank Lloyd Wright' },
  { text: 'The space within becomes the reality of the building.', author: 'Frank Lloyd Wright' },
  { text: 'Design is not just what it looks like and feels like. Design is how it works.', author: 'Steve Jobs' },
  { text: 'Simple can be harder than complex. You have to work hard to get your thinking clean.', author: 'Steve Jobs' },
  { text: 'Details matter, it is worth waiting to get it right.', author: 'Steve Jobs' },
  { text: 'Innovation is saying no to a thousand things.', author: 'Steve Jobs' },
  { text: 'Design is the silent ambassador of your brand.', author: 'Paul Rand' },
  { text: 'Design is so simple, which is why it is so complicated.', author: 'Paul Rand' },
  { text: 'The details are not the details. They make the design.', author: 'Charles Eames' },
  { text: 'Take your pleasure seriously.', author: 'Charles Eames' },
  { text: 'The best design is the one you do not notice.', author: 'Anonymous' },
  { text: 'Good design is as little design as possible.', author: 'Dieter Rams' },
  { text: 'Indifference towards people and the reality in which they live is the one and only cardinal sin in design.', author: 'Dieter Rams' },
  { text: 'Everything is designed. Few things are designed well.', author: 'Brian Reed' },
  { text: 'Measure twice, cut once.', author: 'Carpenter Proverb' },
  { text: 'A craftsman is known by the chips on the floor.', author: 'Anonymous' },
  { text: 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.', author: 'Abraham Lincoln' },
  { text: 'The tools you use shape the work you make.', author: 'Anonymous' },
  { text: 'If a hammer is your only tool, every problem starts to look like a nail.', author: 'Abraham Maslow' },
  { text: 'Any intelligent fool can make things bigger and more complex. It takes genius to move in the opposite direction.', author: 'E F Schumacher' },
  { text: 'Make it work, make it right, make it fast, and always in that order.', author: 'Kent Beck' },
  { text: 'Premature optimisation is the root of all evil.', author: 'Donald Knuth' },
  { text: 'Beware of bugs in the above code, I have only proved it correct, not tried it.', author: 'Donald Knuth' },
  { text: 'The best way to get a project done faster is to start sooner.', author: 'Jim Highsmith' },
  { text: 'Nine people cannot make a baby in a month.', author: 'Fred Brooks' },

  // --- Money, work and enterprise ---
  { text: 'Price is what you pay, value is what you get.', author: 'Warren Buffett' },
  { text: 'Someone is sitting in the shade today because someone planted a tree a long time ago.', author: 'Warren Buffett' },
  { text: 'It takes twenty years to build a reputation and five minutes to ruin it.', author: 'Warren Buffett' },
  { text: 'Rule number one: never lose money. Rule number two: never forget rule number one.', author: 'Warren Buffett' },
  { text: 'Beware of little expenses, a small leak will sink a great ship.', author: 'Benjamin Franklin' },
  { text: 'Do not put off until tomorrow what you can do today.', author: 'Benjamin Franklin' },
  { text: 'A penny saved is a penny earned.', author: 'Benjamin Franklin' },
  { text: 'Never spend your money before you have earned it.', author: 'Thomas Jefferson' },
  { text: 'Wealth is the ability to fully experience life.', author: 'Henry David Thoreau' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'All our dreams can come true if we have the courage to pursue them.', author: 'Walt Disney' },
  { text: 'It is kind of fun to do the impossible.', author: 'Walt Disney' },
  { text: 'Whether you think you can or think you cannot, you are right.', author: 'Henry Ford' },
  { text: 'Coming together is a beginning, keeping together is progress, working together is success.', author: 'Henry Ford' },
  { text: 'If everyone is moving forward together, then success takes care of itself.', author: 'Henry Ford' },
  { text: 'Chop your own wood and it will warm you twice.', author: 'Henry Ford' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
  { text: 'What gets measured gets managed.', author: 'Peter Drucker' },
  { text: 'There is nothing so useless as doing efficiently that which should not be done at all.', author: 'Peter Drucker' },
  { text: 'Culture eats strategy for breakfast.', author: 'Peter Drucker' },
  { text: 'The most important thing in communication is hearing what is not said.', author: 'Peter Drucker' },
  { text: 'Far and away the best prize that life has to offer is the chance to work hard at work worth doing.', author: 'Theodore Roosevelt' },
  { text: 'Opportunity is missed by most people because it comes dressed in overalls and looks like work.', author: 'Thomas Edison' },
  { text: 'There is no substitute for hard work.', author: 'Thomas Edison' },
  { text: 'Our greatest weakness lies in giving up. The certain way to succeed is always to try just one more time.', author: 'Thomas Edison' },

  // --- Teaching and learning ---
  { text: 'Tell me and I forget, teach me and I may remember, involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'The whole art of teaching is only the art of awakening the natural curiosity of young minds.', author: 'Anatole France' },
  { text: 'A child educated only at school is an uneducated child.', author: 'George Santayana' },
  { text: 'Those who cannot remember the past are condemned to repeat it.', author: 'George Santayana' },
  { text: 'To be a teacher of the truth is the greatest calling there is.', author: 'Anonymous' },
  { text: 'The more I learn, the more I realise how much I do not know.', author: 'Albert Einstein' },
  { text: 'Anyone who stops learning is old, whether at twenty or eighty.', author: 'Henry Ford' },
  { text: 'The best teachers are those who show you where to look but do not tell you what to see.', author: 'Alexandra Trenfor' },
  { text: 'What we learn with pleasure we never forget.', author: 'Alfred Mercier' },
  { text: 'Learning is not attained by chance, it must be sought for with ardour and diligence.', author: 'Abigail Adams' },
  { text: 'Curiosity is the wick in the candle of learning.', author: 'William Arthur Ward' },
  { text: 'The mediocre teacher tells, the good teacher explains, the great teacher inspires.', author: 'William Arthur Ward' },
  { text: 'Study without desire spoils the memory, and it retains nothing that it takes in.', author: 'Leonardo da Vinci' },
  { text: 'Do not let schooling interfere with your education.', author: 'Mark Twain' },
  { text: 'I have never let my schooling interfere with my education.', author: 'Grant Allen' },
  { text: 'Education is what remains after one has forgotten what one has learned in school.', author: 'Albert Einstein' },
  { text: 'It is the mark of an educated mind to entertain a thought without accepting it.', author: 'Aristotle' },
  { text: 'The roots of education are bitter, but the fruit is sweet.', author: 'Aristotle' },
  { text: 'Learn as much by writing as by reading.', author: 'John Acton' },
  { text: 'When you talk, you are only repeating what you already know. If you listen, you may learn something new.', author: 'Dalai Lama' },
  { text: 'Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', author: 'Albert Einstein' },
  { text: 'The only person who is educated is the one who has learned how to learn and change.', author: 'Carl Rogers' },
  { text: 'Nothing that is worth knowing can be taught.', author: 'Oscar Wilde' },
  { text: 'A mind that is stretched by a new experience can never go back to its old dimensions.', author: 'Oliver Wendell Holmes' },
  { text: 'Practice does not make perfect. Only perfect practice makes perfect.', author: 'Vince Lombardi' },
  { text: 'If you think education is expensive, try ignorance.', author: 'Derek Bok' },

  // --- Time, patience and habit ---
  { text: 'Patience is bitter, but its fruit is sweet.', author: 'Jean Jacques Rousseau' },
  { text: 'Adopt the pace of the mountain and you will arrive at the summit.', author: 'Anonymous' },
  { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { text: 'Everything comes to him who hustles while he waits.', author: 'Thomas Edison' },
  { text: 'Time is what we want most but what we use worst.', author: 'William Penn' },
  { text: 'Better three hours too soon than a minute too late.', author: 'William Shakespeare' },
  { text: 'We are what we pretend to be, so we must be careful about what we pretend to be.', author: 'Kurt Vonnegut' },
  { text: 'Little strokes fell great oaks.', author: 'Benjamin Franklin' },
  { text: 'Slow and steady wins the race.', author: 'Aesop' },
  { text: 'Rome was not built in a day, but they were laying bricks every hour.', author: 'Anonymous' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Rohn' },
  { text: 'We first make our habits, and then our habits make us.', author: 'John Dryden' },
  { text: 'The chains of habit are too weak to be felt until they are too strong to be broken.', author: 'Samuel Johnson' },
  { text: 'Great things are not accomplished by those who yield to trends and fads and popular opinion.', author: 'Jack Kerouac' },
  { text: 'You do not rise to the level of your goals, you fall to the level of your systems.', author: 'James Clear' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'The best time for new beginnings is now.', author: 'Anonymous' },
  { text: 'Do not wait. The time will never be just right.', author: 'Napoleon Hill' },
  { text: 'Tomorrow is often the busiest day of the week.', author: 'Spanish Proverb' },
  { text: 'One today is worth two tomorrows.', author: 'Benjamin Franklin' },
  { text: 'Nothing is more expensive than a missed opportunity.', author: 'H Jackson Brown Jr' },
  { text: 'You will never find time for anything. If you want time you must make it.', author: 'Charles Buxton' },
  { text: 'Time flies over us but leaves its shadow behind.', author: 'Nathaniel Hawthorne' },
  { text: 'The trouble is, you think you have time.', author: 'Jack Kornfield' },
  { text: 'Yesterday is gone, tomorrow has not yet come. We have only today, so let us begin.', author: 'Mother Teresa' },

  // --- Kindness, friendship and family ---
  { text: 'No act of kindness, no matter how small, is ever wasted.', author: 'Aesop' },
  { text: 'Kindness is a language which the deaf can hear and the blind can see.', author: 'Mark Twain' },
  { text: 'Carry out a random act of kindness with no expectation of reward.', author: 'Princess Diana' },
  { text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank' },
  { text: 'Whoever is happy will make others happy too.', author: 'Anne Frank' },
  { text: 'No one has ever become poor by giving.', author: 'Anne Frank' },
  { text: 'Spread love everywhere you go. Let no one ever come to you without leaving happier.', author: 'Mother Teresa' },
  { text: 'If you cannot feed a hundred people, then feed just one.', author: 'Mother Teresa' },
  { text: 'Not all of us can do great things, but we can do small things with great love.', author: 'Mother Teresa' },
  { text: 'Be kind whenever possible. It is always possible.', author: 'Dalai Lama' },
  { text: 'A friend is someone who knows all about you and still loves you.', author: 'Elbert Hubbard' },
  { text: 'Friendship is the only cement that will ever hold the world together.', author: 'Woodrow Wilson' },
  { text: 'A single rose can be my garden, a single friend my world.', author: 'Leo Buscaglia' },
  { text: 'Walking with a friend in the dark is better than walking alone in the light.', author: 'Helen Keller' },
  { text: 'True friendship comes when the silence between two people is comfortable.', author: 'David Tyson' },
  { text: 'Friends are the family you choose.', author: 'Jess C Scott' },
  { text: 'A brother is a friend given by nature.', author: 'Jean Baptiste Legouve' },
  { text: 'Family is not an important thing, it is everything.', author: 'Michael J Fox' },
  { text: 'The most important thing in the world is family and love.', author: 'John Wooden' },
  { text: 'Home is where love resides, memories are created, and friends always belong.', author: 'Anonymous' },
  { text: 'To the world you may be one person, but to one person you may be the world.', author: 'Bill Wilson' },
  { text: 'We rise by lifting others.', author: 'Robert Ingersoll' },
  { text: 'Everyone you meet is fighting a battle you know nothing about. Be kind, always.', author: 'Anonymous' },
  { text: 'The best way to cheer yourself is to try to cheer someone else up.', author: 'Mark Twain' },
  { text: 'A kind word is like a spring day.', author: 'Russian Proverb' },
  { text: 'Do things for people not because of who they are or what they do in return, but because of who you are.', author: 'Harold Kushner' },
  { text: 'What we have once enjoyed we can never lose. All that we love deeply becomes a part of us.', author: 'Helen Keller' },
  { text: 'Love and kindness are never wasted. They always make a difference.', author: 'Barbara De Angelis' },
  { text: 'We cannot help everyone, but everyone can help someone.', author: 'Ronald Reagan' },
  { text: 'Wherever there is a human being there is an opportunity for kindness.', author: 'Lucius Annaeus Seneca' },
  { text: 'Gratitude turns what we have into enough.', author: 'Anonymous' },
  { text: 'Be the reason someone believes in the goodness of people.', author: 'Anonymous' },
  { text: 'Nobody cares how much you know until they know how much you care.', author: 'Theodore Roosevelt' },
  { text: 'A smile is the shortest distance between two people.', author: 'Victor Borge' },

  // --- More wit and mischief ---
  { text: 'True friends stab you in the front.', author: 'Oscar Wilde' },
  { text: 'The only thing worse than being talked about is not being talked about.', author: 'Oscar Wilde' },
  { text: 'I am not young enough to know everything.', author: 'J M Barrie' },
  { text: 'The reports of my death are greatly exaggerated.', author: 'Mark Twain' },
  { text: 'When in doubt, tell the truth.', author: 'Mark Twain' },
  { text: 'Never put off till tomorrow what may be done day after tomorrow just as well.', author: 'Mark Twain' },
  { text: 'It is better to keep your mouth closed and let people think you are a fool than to open it and prove it.', author: 'Mark Twain' },
  { text: 'I have never been hurt by anything I did not say.', author: 'Calvin Coolidge' },
  { text: 'A lie gets halfway around the world before the truth has a chance to get its trousers on.', author: 'Winston Churchill' },
  { text: 'I am easily satisfied with the very best.', author: 'Winston Churchill' },
  { text: 'History will be kind to me, for I intend to write it.', author: 'Winston Churchill' },
  { text: 'Everything is funny as long as it is happening to somebody else.', author: 'Will Rogers' },
  { text: 'Never miss a good chance to shut up.', author: 'Will Rogers' },
  { text: 'Even if you are on the right track, you will get run over if you just sit there.', author: 'Will Rogers' },
  { text: 'I am not a member of any organised political party, I am a democrat.', author: 'Will Rogers' },
  { text: 'The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt.', author: 'Bertrand Russell' },
  { text: 'The time you enjoy wasting is not wasted time.', author: 'Bertrand Russell' },
  { text: 'I love deadlines. I love the whooshing noise they make as they go by.', author: 'Douglas Adams' },
  { text: 'The ships hung in the sky in much the same way that bricks do not.', author: 'Douglas Adams' },
  { text: 'I may not have gone where I intended to go, but I think I have ended up where I needed to be.', author: 'Douglas Adams' },
  { text: 'Anyone who is capable of getting themselves made president should on no account be allowed to do the job.', author: 'Douglas Adams' },
  { text: 'A common mistake people make when trying to design something foolproof is to underestimate the ingenuity of fools.', author: 'Douglas Adams' },
  { text: 'Nothing travels faster than the speed of light, with the possible exception of bad news.', author: 'Douglas Adams' },
  { text: 'I have not lost my mind, it is backed up on tape somewhere.', author: 'Anonymous' },

  // --- More longer passages, for the hard tier ---
  { text: 'It is not the critic who counts, nor the one who points out how the strong man stumbles, but the one who is in the arena.', author: 'Theodore Roosevelt' },
  { text: 'Comparison is the thief of joy, and the fastest way to lose what you already have is to measure it against someone else.', author: 'Theodore Roosevelt' },
  { text: 'The most beautiful thing we can experience is the mysterious. It is the source of all true art and all science.', author: 'Albert Einstein' },
  { text: 'Try not to become a man of success, but rather try to become a man of value, for that is what endures.', author: 'Albert Einstein' },
  { text: 'A human being is part of a whole, called by us the universe, a part limited in time and space.', author: 'Albert Einstein' },
  { text: 'Life is like riding a bicycle. To keep your balance you must keep moving forward, whatever the road does.', author: 'Albert Einstein' },
  { text: 'If you want to live a happy life, tie it to a goal, not to people or to things that can be taken away.', author: 'Albert Einstein' },
  { text: 'Any fool can know. The point is to understand, and understanding takes far longer than anybody expects.', author: 'Albert Einstein' },
  { text: 'The world is a book and those who do not travel read only one page of it in their whole lives.', author: 'Saint Augustine' },
  { text: 'People say that what we are all seeking is a meaning for life, but I think we are seeking an experience of being alive.', author: 'Joseph Campbell' },
  { text: 'The cave you fear to enter holds the treasure you seek, and the only way past it is through it.', author: 'Joseph Campbell' },
  { text: 'We must be willing to let go of the life we planned so as to have the life that is waiting for us.', author: 'Joseph Campbell' },
  { text: 'Life is what happens to you while you are busy making other plans, and it rarely asks permission first.', author: 'Allen Saunders' },
  { text: 'Between stimulus and response there is a space, and in that space lies our freedom to choose our reply.', author: 'Viktor Frankl' },
  { text: 'When we are no longer able to change a situation, we are challenged to change ourselves instead.', author: 'Viktor Frankl' },
  { text: 'Those who have a why to live can bear with almost any how, and that is the whole of the matter.', author: 'Viktor Frankl' },
  { text: 'What you get by achieving your goals is not as important as what you become by achieving them.', author: 'Zig Ziglar' },
  { text: 'You do not have to be great to start, but you have to start to be great, and starting is the hard part.', author: 'Zig Ziglar' },
  { text: 'The greatest discovery of my generation is that human beings can alter their lives by altering their attitudes.', author: 'William James' },
  { text: 'If you can dream it you can do it, and always remember that this whole thing started with a mouse.', author: 'Walt Disney' },
  { text: 'Around here we do not look backwards for very long. We keep moving forward, opening up new doors.', author: 'Walt Disney' },
  { text: 'The best way to find out if you can trust somebody is to trust them, and then to watch what they do.', author: 'Ernest Hemingway' },
  { text: 'There is nothing noble in being superior to your fellow man. True nobility is being superior to your former self.', author: 'Ernest Hemingway' },
  { text: 'Courage is grace under pressure, and grace is what remains when the pressure has taken everything else.', author: 'Ernest Hemingway' },
  { text: 'Every man has two lives, and the second one begins when he realises that he has only one.', author: 'Confucius' },
  { text: 'When it is obvious that the goals cannot be reached, do not adjust the goals, adjust the action steps.', author: 'Confucius' },
  { text: 'Life is really simple, but we insist on making it complicated, and then we call the result experience.', author: 'Confucius' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall along the way.', author: 'Confucius' },
  { text: 'Wherever you go, go with all your heart, and do not leave half of yourself behind at the door.', author: 'Confucius' },
  { text: 'The journey of a thousand miles begins beneath your feet, so look down before you look ahead.', author: 'Lao Tzu' },
  { text: 'When I let go of what I am, I become what I might be, and that is the whole trick of it.', author: 'Lao Tzu' },
  { text: 'To attain knowledge, add things every day. To attain wisdom, remove things every day instead.', author: 'Lao Tzu' },
  { text: 'Mastering others is strength. Mastering yourself is true power, and far the harder of the two.', author: 'Lao Tzu' },
  { text: 'Be content with what you have, rejoice in the way things are, and nothing at all will be missing.', author: 'Lao Tzu' },
  { text: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', author: 'Buddha' },
  { text: 'You yourself, as much as anybody in the entire universe, deserve your love and your affection.', author: 'Buddha' },
  { text: 'Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else.', author: 'Buddha' },
  { text: 'What we think, we become, and every thought we repeat is a brick laid in the house we live in.', author: 'Buddha' },
  { text: 'Better than a thousand hollow words is one word that brings peace to the person who hears it.', author: 'Buddha' },
  { text: 'The best fighter is never angry, and the calmest hand on the table is usually the one that wins.', author: 'Lao Tzu' },
  { text: 'It is not death that a man should fear, but he should fear never beginning to live at all.', author: 'Marcus Aurelius' },
  { text: 'The soul becomes dyed with the colour of its thoughts, so guard well what you allow into it.', author: 'Marcus Aurelius' },
  { text: 'If it is not right, do not do it. If it is not true, do not say it. That is the whole of the rule.', author: 'Marcus Aurelius' },
  { text: 'Very little is needed to make a happy life. It is all within yourself, in your way of thinking.', author: 'Marcus Aurelius' },
  { text: 'Confine yourself to the present, and let the future arrive on its own terms and in its own time.', author: 'Marcus Aurelius' },
  { text: 'Difficulties strengthen the mind as labour does the body, and neither grows without resistance.', author: 'Lucius Annaeus Seneca' },
  { text: 'Begin at once to live, and count each separate day as a separate life that has been given to you.', author: 'Lucius Annaeus Seneca' },
  { text: 'As long as you live, keep learning how to live, for nobody arrives already knowing the trade.', author: 'Lucius Annaeus Seneca' },
  { text: 'While we wait for life, life passes by, and the waiting turns out to have been the whole of it.', author: 'Lucius Annaeus Seneca' },
  { text: 'It is not the man who has too little, but the man who craves more, who is properly called poor.', author: 'Lucius Annaeus Seneca' },
  { text: 'No great thing is created suddenly, any more than a bunch of grapes or a fig can ripen overnight.', author: 'Epictetus' },
  { text: 'We have two ears and one mouth so that we can listen twice as much as we speak to each other.', author: 'Epictetus' },
  { text: 'First say to yourself what you would be, and then do what you have to do to become that thing.', author: 'Epictetus' },
  { text: 'Circumstances do not make the man, they only reveal him to himself and to everybody watching.', author: 'Epictetus' },
  { text: 'The key is to keep company only with people who uplift you, whose presence calls forth your best.', author: 'Epictetus' },
  { text: 'A ship in harbour is safe, but that is not at all what ships are built for in the first place.', author: 'John A Shedd' },
  { text: 'The pain you feel today will be the strength you feel tomorrow, provided you keep walking through it.', author: 'Anonymous' },
  { text: 'Do not be afraid of going slowly, be afraid only of standing still and calling it a rest.', author: 'Chinese Proverb' },
  { text: 'Fall seven times and stand up eight, because the standing up is the only part that gets counted.', author: 'Japanese Proverb' },
  { text: 'A journey is best measured in friends rather than in miles, and in stories rather than in hours.', author: 'Tim Cahill' },
  { text: 'Travel far enough and you meet yourself, usually at the moment you had stopped looking for anybody.', author: 'David Mitchell' },
  { text: 'The real voyage of discovery consists not in seeking new landscapes but in having new eyes.', author: 'Marcel Proust' },
  { text: 'Let us be grateful to people who make us happy, for they are the charming gardeners of the soul.', author: 'Marcel Proust' },
  { text: 'We do not remember days, we remember moments, and most of them arrive without any warning at all.', author: 'Cesare Pavese' },
];

/**
 * Development aid: reports quotes that break the house rules. Called from
 * main.js only when running on localhost, so it never costs anything in
 * production. Returns the list of problems rather than throwing, because one
 * bad quote should never stop the game from loading.
 * @param {Array<{text: string, author: string}>} quotes
 * @returns {string[]}
 */
export function validateQuotes(quotes = QUOTES) {
  const problems = [];
  const seen = new Set();

  quotes.forEach((quote, i) => {
    const label = `#${i} "${quote.text.slice(0, 40)}..."`;

    if (!quote.text || !quote.author) {
      problems.push(`${label}: missing text or author`);
      return;
    }
    // eslint-disable-next-line no-control-regex
    if (/[^\x20-\x7E]/.test(quote.text)) {
      problems.push(`${label}: contains non-ASCII characters`);
    }
    if (quote.text.length < 20) {
      problems.push(`${label}: too short (${quote.text.length} chars)`);
    }
    if (quote.text.length > 160) {
      problems.push(`${label}: too long (${quote.text.length} chars)`);
    }
    if (!/[A-Za-z]/.test(quote.text)) {
      problems.push(`${label}: no letters to encrypt`);
    }

    const key = quote.text.toLowerCase().replace(/[^a-z]/g, '');
    if (seen.has(key)) problems.push(`${label}: duplicate`);
    seen.add(key);
  });

  return problems;
}

/**
 * Quotes filtered to a difficulty band. Length is the main lever on how long a
 * puzzle takes, so each tier gets its own slice of the pack.
 * @param {'easy'|'medium'|'hard'} difficulty
 * @returns {Array<{text: string, author: string}>}
 */
export function quotesForDifficulty(difficulty) {
  const bands = {
    easy: [20, 70],
    medium: [50, 110],
    hard: [80, 200],
  };
  const [min, max] = bands[difficulty] ?? bands.medium;
  const pool = QUOTES.filter((q) => q.text.length >= min && q.text.length <= max);
  // Never hand back an empty pool: a narrow band on a small pack would
  // otherwise make the game unplayable at that difficulty.
  return pool.length >= 10 ? pool : QUOTES;
}
