// Bundled quote pack.
//
// House rules, because they directly affect whether a puzzle is fun:
//   - 40-160 characters. Shorter gives too little signal to deduce from;
//     longer is a slog on a phone screen.
//   - ASCII only. Curly quotes, em-dashes and accents break cell alignment
//     and have no key on the on-screen keyboard.
//   - Stored as written; uppercased at render time.
//
// Add your own by appending to this array. `validateQuotes()` below will warn
// in the console about anything that breaks the rules.

export const QUOTES = [
  // --- Wisdom and philosophy ---
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'I know that I know nothing at all.', author: 'Socrates' },
  { text: 'We are what we repeatedly do. Excellence is a habit.', author: 'Aristotle' },
  { text: 'The whole is greater than the sum of its parts.', author: 'Aristotle' },
  { text: 'Happiness depends upon ourselves.', author: 'Aristotle' },
  { text: 'No man ever steps in the same river twice.', author: 'Heraclitus' },
  { text: 'Waste no more time arguing what a good man should be. Be one.', author: 'Marcus Aurelius' },
  { text: 'You have power over your mind, not outside events.', author: 'Marcus Aurelius' },
  { text: 'The happiness of your life depends upon the quality of your thoughts.', author: 'Marcus Aurelius' },
  { text: 'We suffer more often in imagination than in reality.', author: 'Seneca' },
  { text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca' },
  { text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca' },
  { text: 'It is impossible to learn that which one thinks one already knows.', author: 'Epictetus' },
  { text: 'Wealth consists not in having great possessions but in having few wants.', author: 'Epictetus' },
  { text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'Knowing others is wisdom. Knowing yourself is enlightenment.', author: 'Lao Tzu' },
  { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Real knowledge is to know the extent of one ignorance.', author: 'Confucius' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'Everything has beauty, but not everyone sees it.', author: 'Confucius' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'Three things cannot be long hidden: the sun, the moon, and the truth.', author: 'Buddha' },
  { text: 'Peace comes from within. Do not seek it without.', author: 'Buddha' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'Man is condemned to be free.', author: 'Jean-Paul Sartre' },
  { text: 'Life must be understood backwards, but it must be lived forwards.', author: 'Soren Kierkegaard' },
  { text: 'The limits of my language mean the limits of my world.', author: 'Ludwig Wittgenstein' },
  { text: 'I think, therefore I am.', author: 'Rene Descartes' },
  { text: 'Doubt is the origin of wisdom.', author: 'Rene Descartes' },
  { text: 'Liberty consists in doing what one desires.', author: 'John Stuart Mill' },
  { text: 'The only thing necessary for evil to triumph is for good men to do nothing.', author: 'Edmund Burke' },

  // --- Science, discovery and the mind ---
  { text: 'Imagination is more important than knowledge.', author: 'Albert Einstein' },
  { text: 'Try not to become a man of success, but rather a man of value.', author: 'Albert Einstein' },
  { text: 'The important thing is not to stop questioning.', author: 'Albert Einstein' },
  { text: 'Anyone who has never made a mistake has never tried anything new.', author: 'Albert Einstein' },
  { text: 'Life is like riding a bicycle. To keep your balance you must keep moving.', author: 'Albert Einstein' },
  { text: 'If I have seen further it is by standing on the shoulders of giants.', author: 'Isaac Newton' },
  { text: 'Nothing in life is to be feared, it is only to be understood.', author: 'Marie Curie' },
  { text: 'Be less curious about people and more curious about ideas.', author: 'Marie Curie' },
  { text: 'Somewhere, something incredible is waiting to be known.', author: 'Carl Sagan' },
  { text: 'We are made of star stuff.', author: 'Carl Sagan' },
  { text: 'Extraordinary claims require extraordinary evidence.', author: 'Carl Sagan' },
  { text: 'The first principle is that you must not fool yourself.', author: 'Richard Feynman' },
  { text: 'I would rather have questions that cannot be answered than answers that cannot be questioned.', author: 'Richard Feynman' },
  { text: 'Study hard what interests you the most in the most undisciplined way possible.', author: 'Richard Feynman' },
  { text: 'It is not the strongest of the species that survives, but the most adaptable.', author: 'Charles Darwin' },
  { text: 'A man who dares to waste one hour of time has not discovered the value of life.', author: 'Charles Darwin' },
  { text: 'Science is a way of thinking much more than it is a body of knowledge.', author: 'Carl Sagan' },
  { text: 'Equipped with his five senses, man explores the universe around him.', author: 'Edwin Hubble' },
  { text: 'Look up at the stars and not down at your feet.', author: 'Stephen Hawking' },
  { text: 'Intelligence is the ability to adapt to change.', author: 'Stephen Hawking' },
  { text: 'The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.', author: 'Stephen Hawking' },
  { text: 'What we know is a drop, what we do not know is an ocean.', author: 'Isaac Newton' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'Chance favors the prepared mind.', author: 'Louis Pasteur' },
  { text: 'Nothing has such power to broaden the mind as the ability to investigate.', author: 'Marcus Aurelius' },

  // --- Writers and poets ---
  { text: 'The two most powerful warriors are patience and time.', author: 'Leo Tolstoy' },
  { text: 'Everyone thinks of changing the world, but no one thinks of changing himself.', author: 'Leo Tolstoy' },
  { text: 'It is better to be hated for what you are than loved for what you are not.', author: 'Andre Gide' },
  { text: 'There is no greater agony than bearing an untold story inside you.', author: 'Maya Angelou' },
  { text: 'You may not control all the events that happen to you, but you can decide not to be reduced by them.', author: 'Maya Angelou' },
  { text: 'We write to taste life twice, in the moment and in retrospect.', author: 'Anais Nin' },
  { text: 'We do not see things as they are, we see them as we are.', author: 'Anais Nin' },
  { text: 'A room without books is like a body without a soul.', author: 'Marcus Tullius Cicero' },
  { text: 'The world is a book and those who do not travel read only one page.', author: 'Saint Augustine' },
  { text: 'Not all those who wander are lost.', author: 'J R R Tolkien' },
  { text: 'All we have to decide is what to do with the time that is given us.', author: 'J R R Tolkien' },
  { text: 'It is a truth universally acknowledged that a single man must want a wife.', author: 'Jane Austen' },
  { text: 'There is no charm equal to tenderness of heart.', author: 'Jane Austen' },
  { text: 'It was the best of times, it was the worst of times.', author: 'Charles Dickens' },
  { text: 'No one is useless in this world who lightens the burden of another.', author: 'Charles Dickens' },
  { text: 'The only way out of the labyrinth of suffering is to forgive.', author: 'John Green' },
  { text: 'Beware, for I am fearless, and therefore powerful.', author: 'Mary Shelley' },
  { text: 'I am no bird, and no net ensnares me.', author: 'Charlotte Bronte' },
  { text: 'Whatever our souls are made of, his and mine are the same.', author: 'Emily Bronte' },
  { text: 'Hope is the thing with feathers that perches in the soul.', author: 'Emily Dickinson' },
  { text: 'Tell all the truth but tell it slant.', author: 'Emily Dickinson' },
  { text: 'I took the one less traveled by, and that has made all the difference.', author: 'Robert Frost' },
  { text: 'In three words I can sum up everything I have learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'Do I dare disturb the universe?', author: 'T S Eliot' },
  { text: 'Only those who risk going too far can possibly find out how far one can go.', author: 'T S Eliot' },
  { text: 'The heart wants what it wants, or else it does not care.', author: 'Emily Dickinson' },
  { text: 'And so we beat on, boats against the current.', author: 'F Scott Fitzgerald' },
  { text: 'So we drove on toward death through the cooling twilight.', author: 'F Scott Fitzgerald' },
  { text: 'There is nothing to writing. You just sit at a typewriter and bleed.', author: 'Ernest Hemingway' },
  { text: 'The world breaks everyone, and afterward many are strong at the broken places.', author: 'Ernest Hemingway' },
  { text: 'A man can be destroyed but not defeated.', author: 'Ernest Hemingway' },
  { text: 'It is not down on any map, true places never are.', author: 'Herman Melville' },
  { text: 'I would prefer not to.', author: 'Herman Melville' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'Big Brother is watching you.', author: 'George Orwell' },
  { text: 'If liberty means anything at all, it means the right to tell people what they do not want to hear.', author: 'George Orwell' },
  { text: 'In a time of deceit, telling the truth is a revolutionary act.', author: 'George Orwell' },
  { text: 'It is no measure of health to be well adjusted to a profoundly sick society.', author: 'Jiddu Krishnamurti' },
  { text: 'A word after a word after a word is power.', author: 'Margaret Atwood' },
  { text: 'You never really understand a person until you climb into his skin and walk around in it.', author: 'Harper Lee' },
  { text: 'People generally see what they look for and hear what they listen for.', author: 'Harper Lee' },
  { text: 'It is such a happiness when good people get together.', author: 'Jane Austen' },
  { text: 'The answer, my friend, is blowing in the wind.', author: 'Bob Dylan' },
  { text: 'I dwell in possibility.', author: 'Emily Dickinson' },
  { text: 'Do not go gentle into that good night.', author: 'Dylan Thomas' },
  { text: 'Poetry is what gets lost in translation.', author: 'Robert Frost' },
  { text: 'Wherever they burn books, they will also burn people in the end.', author: 'Heinrich Heine' },

  // --- Mark Twain and the wits ---
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Kindness is the language which the deaf can hear and the blind can see.', author: 'Mark Twain' },
  { text: 'Whenever you find yourself on the side of the majority, it is time to pause.', author: 'Mark Twain' },
  { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
  { text: 'Never let schooling interfere with your education.', author: 'Mark Twain' },
  { text: 'It is easier to fool people than to convince them they have been fooled.', author: 'Mark Twain' },
  { text: 'A lie can travel halfway around the world while the truth is putting on its shoes.', author: 'Mark Twain' },
  { text: 'Age is an issue of mind over matter. If you do not mind, it does not matter.', author: 'Mark Twain' },
  { text: 'Be yourself, everyone else is already taken.', author: 'Oscar Wilde' },
  { text: 'We are all in the gutter, but some of us are looking at the stars.', author: 'Oscar Wilde' },
  { text: 'I can resist everything except temptation.', author: 'Oscar Wilde' },
  { text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde' },
  { text: 'Experience is simply the name we give our mistakes.', author: 'Oscar Wilde' },
  { text: 'The only way to get rid of a temptation is to yield to it.', author: 'Oscar Wilde' },
  { text: 'Always forgive your enemies, nothing annoys them so much.', author: 'Oscar Wilde' },
  { text: 'I have nothing to declare except my genius.', author: 'Oscar Wilde' },
  { text: 'A cynic knows the price of everything and the value of nothing.', author: 'Oscar Wilde' },
  { text: 'The trouble with the world is that the stupid are cocksure and the intelligent full of doubt.', author: 'Bertrand Russell' },
  { text: 'Do not take life too seriously. You will never get out of it alive.', author: 'Elbert Hubbard' },
  { text: 'I have not failed. I have just found ten thousand ways that will not work.', author: 'Thomas Edison' },
  { text: 'Genius is one percent inspiration and ninety nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'Everything you can imagine is real.', author: 'Pablo Picasso' },
  { text: 'Every child is an artist. The problem is staying an artist when you grow up.', author: 'Pablo Picasso' },
  { text: 'Good artists copy, great artists steal.', author: 'Pablo Picasso' },
  { text: 'Wit is educated insolence.', author: 'Aristotle' },
  { text: 'I am so clever that sometimes I do not understand a single word of what I am saying.', author: 'Oscar Wilde' },
  { text: 'The road to success is always under construction.', author: 'Lily Tomlin' },
  { text: 'I always wanted to be somebody, but now I realize I should have been more specific.', author: 'Lily Tomlin' },
  { text: 'A day without laughter is a day wasted.', author: 'Charlie Chaplin' },
  { text: 'Life is a tragedy when seen in close up, but a comedy in long shot.', author: 'Charlie Chaplin' },
  { text: 'Nothing is softer or more flexible than water, yet nothing can resist it.', author: 'Lao Tzu' },
  { text: 'Behind every great fortune there is a crime.', author: 'Honore de Balzac' },
  { text: 'I refuse to join any club that would have me as a member.', author: 'Groucho Marx' },
  { text: 'Outside of a dog, a book is a man best friend.', author: 'Groucho Marx' },
  { text: 'Time flies like an arrow. Fruit flies like a banana.', author: 'Groucho Marx' },
  { text: 'Anyone who lives within their means suffers from a lack of imagination.', author: 'Oscar Wilde' },
  { text: 'Get your facts first, then you can distort them as you please.', author: 'Mark Twain' },
  { text: 'Better to remain silent and be thought a fool than to speak and remove all doubt.', author: 'Mark Twain' },
  { text: 'Clothes make the man. Naked people have little or no influence on society.', author: 'Mark Twain' },

  // --- Leaders, courage and change ---
  { text: 'The only thing we have to fear is fear itself.', author: 'Franklin D Roosevelt' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'Believe you can and you are halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Comparison is the thief of joy.', author: 'Theodore Roosevelt' },
  { text: 'Nothing worth having comes easy.', author: 'Theodore Roosevelt' },
  { text: 'Success is not final, failure is not fatal, it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'If you are going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'Never was so much owed by so many to so few.', author: 'Winston Churchill' },
  { text: 'Attitude is a little thing that makes a big difference.', author: 'Winston Churchill' },
  { text: 'We shall fight on the beaches, we shall never surrender.', author: 'Winston Churchill' },
  { text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'An eye for an eye only ends up making the whole world blind.', author: 'Mahatma Gandhi' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
  { text: 'Darkness cannot drive out darkness, only light can do that.', author: 'Martin Luther King Jr' },
  { text: 'The time is always right to do what is right.', author: 'Martin Luther King Jr' },
  { text: 'Injustice anywhere is a threat to justice everywhere.', author: 'Martin Luther King Jr' },
  { text: 'Our lives begin to end the day we become silent about things that matter.', author: 'Martin Luther King Jr' },
  { text: 'Faith is taking the first step even when you do not see the whole staircase.', author: 'Martin Luther King Jr' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'A winner is a dreamer who never gives up.', author: 'Nelson Mandela' },
  { text: 'The brave man is not he who does not feel afraid, but he who conquers that fear.', author: 'Nelson Mandela' },
  { text: 'No one is born hating another person because of the color of his skin.', author: 'Nelson Mandela' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
  { text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
  { text: 'Great minds discuss ideas, average minds discuss events, small minds discuss people.', author: 'Eleanor Roosevelt' },
  { text: 'Ask not what your country can do for you, ask what you can do for your country.', author: 'John F Kennedy' },
  { text: 'Change is the law of life, and those who look only to the past will miss the future.', author: 'John F Kennedy' },
  { text: 'A rising tide lifts all the boats.', author: 'John F Kennedy' },
  { text: 'Those who dare to fail miserably can achieve greatly.', author: 'Robert F Kennedy' },
  { text: 'Well behaved women seldom make history.', author: 'Laurel Thatcher Ulrich' },
  { text: 'I have learned over the years that when one mind is made up, fear diminishes.', author: 'Rosa Parks' },
  { text: 'You must do the things you think you cannot do.', author: 'Eleanor Roosevelt' },
  { text: 'Freedom is never given, it is won.', author: 'A Philip Randolph' },
  { text: 'We are here not because we are law breakers, we are here in our efforts to become law makers.', author: 'Emmeline Pankhurst' },
  { text: 'I would rather be a rebel than a slave.', author: 'Emmeline Pankhurst' },
  { text: 'None of us is as smart as all of us.', author: 'Ken Blanchard' },

  // --- Work, craft and creativity ---
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { text: 'Innovation distinguishes between a leader and a follower.', author: 'Steve Jobs' },
  { text: 'Design is not just what it looks like. Design is how it works.', author: 'Steve Jobs' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'Art is never finished, only abandoned.', author: 'Leonardo da Vinci' },
  { text: 'Obstacles cannot crush me. Every obstacle yields to stern resolve.', author: 'Leonardo da Vinci' },
  { text: 'I am still learning.', author: 'Michelangelo' },
  { text: 'The greater danger is not that our aim is too high and we miss it, but too low and we reach it.', author: 'Michelangelo' },
  { text: 'Whether you think you can or you think you cannot, you are right.', author: 'Henry Ford' },
  { text: 'Coming together is a beginning, staying together is progress, working together is success.', author: 'Henry Ford' },
  { text: 'Quality means doing it right when no one is looking.', author: 'Henry Ford' },
  { text: 'Failure is simply the opportunity to begin again, more intelligently.', author: 'Henry Ford' },
  { text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Chinese Proverb' },
  { text: 'Perfection is achieved when there is nothing left to take away.', author: 'Antoine de Saint-Exupery' },
  { text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupery' },
  { text: 'If you want to build a ship, teach people to long for the endless sea.', author: 'Antoine de Saint-Exupery' },
  { text: 'It is the time you have spent on your rose that makes your rose so important.', author: 'Antoine de Saint-Exupery' },
  { text: 'What is essential is invisible to the eye.', author: 'Antoine de Saint-Exupery' },
  { text: 'Creativity is intelligence having fun.', author: 'Albert Einstein' },
  { text: 'You cannot use up creativity. The more you use, the more you have.', author: 'Maya Angelou' },
  { text: 'Do not wait for inspiration. It comes while working.', author: 'Henri Matisse' },
  { text: 'Have no fear of perfection, you will never reach it.', author: 'Salvador Dali' },
  { text: 'Every artist was first an amateur.', author: 'Ralph Waldo Emerson' },
  { text: 'Do not go where the path may lead, go instead where there is no path.', author: 'Ralph Waldo Emerson' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'To be yourself in a world constantly trying to make you something else is an achievement.', author: 'Ralph Waldo Emerson' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'Go confidently in the direction of your dreams.', author: 'Henry David Thoreau' },
  { text: 'I went to the woods because I wished to live deliberately.', author: 'Henry David Thoreau' },
  { text: 'The price of anything is the amount of life you exchange for it.', author: 'Henry David Thoreau' },
  { text: 'It is not enough to be busy. The question is, what are we busy about?', author: 'Henry David Thoreau' },
  { text: 'Our life is frittered away by detail. Simplify, simplify.', author: 'Henry David Thoreau' },
  { text: 'Programs must be written for people to read, and only incidentally for machines.', author: 'Harold Abelson' },
  { text: 'Any fool can write code that a computer can understand. Good programmers write code humans understand.', author: 'Martin Fowler' },
  { text: 'Talk is cheap. Show me the code.', author: 'Linus Torvalds' },
  { text: 'First, solve the problem. Then, write the code.', author: 'John Johnson' },
  { text: 'Premature optimization is the root of all evil.', author: 'Donald Knuth' },
  { text: 'Walking on water and developing software from a specification are easy if both are frozen.', author: 'Edward Berard' },
  { text: 'There are only two hard things in computer science: cache invalidation and naming things.', author: 'Phil Karlton' },
  { text: 'Machines take me by surprise with great frequency.', author: 'Alan Turing' },
  { text: 'Those who can imagine anything can create the impossible.', author: 'Alan Turing' },
  { text: 'Sometimes it is the people no one imagines anything of who do the things no one can imagine.', author: 'Alan Turing' },
  { text: 'The most damaging phrase in the language is: we have always done it this way.', author: 'Grace Hopper' },
  { text: 'A ship in port is safe, but that is not what ships are built for.', author: 'Grace Hopper' },

  // --- Persistence, failure and grit ---
  { text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb' },
  { text: 'Success is stumbling from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'It does not matter how many times you fail. You only have to be right once.', author: 'Mark Cuban' },
  { text: 'I have missed more than nine thousand shots in my career. That is why I succeed.', author: 'Michael Jordan' },
  { text: 'You miss one hundred percent of the shots you do not take.', author: 'Wayne Gretzky' },
  { text: 'Hard work beats talent when talent does not work hard.', author: 'Tim Notke' },
  { text: 'The harder I practice, the luckier I get.', author: 'Gary Player' },
  { text: 'It is not the size of the dog in the fight, but the size of the fight in the dog.', author: 'Mark Twain' },
  { text: 'Champions keep playing until they get it right.', author: 'Billie Jean King' },
  { text: 'Pressure is a privilege.', author: 'Billie Jean King' },
  { text: 'Float like a butterfly, sting like a bee.', author: 'Muhammad Ali' },
  { text: 'Do not count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'The fight is won far away from witnesses, behind the lines, in the gym.', author: 'Muhammad Ali' },
  { text: 'It is hard to beat a person who never gives up.', author: 'Babe Ruth' },
  { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
  { text: 'It ain over till it over.', author: 'Yogi Berra' },
  { text: 'When you come to a fork in the road, take it.', author: 'Yogi Berra' },
  { text: 'In theory there is no difference between theory and practice. In practice there is.', author: 'Yogi Berra' },
  { text: 'Nobody goes there anymore, it is too crowded.', author: 'Yogi Berra' },
  { text: 'You cannot cross the sea merely by standing and staring at the water.', author: 'Rabindranath Tagore' },
  { text: 'The bamboo that bends is stronger than the oak that resists.', author: 'Japanese Proverb' },
  { text: 'Smooth seas do not make skillful sailors.', author: 'African Proverb' },
  { text: 'If you want to go fast, go alone. If you want to go far, go together.', author: 'African Proverb' },
  { text: 'A river cuts through rock not because of its power but its persistence.', author: 'Jim Watkins' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius' },
  { text: 'Rock bottom became the solid foundation on which I rebuilt my life.', author: 'J K Rowling' },
  { text: 'It is our choices that show what we truly are, far more than our abilities.', author: 'J K Rowling' },
  { text: 'Happiness can be found even in the darkest of times if one remembers to turn on the light.', author: 'J K Rowling' },
  { text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
  { text: 'Everything is hard before it is easy.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Whatever you can do or dream you can, begin it. Boldness has genius in it.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Knowing is not enough, we must apply. Willing is not enough, we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein' },

  // --- Curious facts and history ---
  { text: 'Honey never spoils. Jars found in ancient tombs are still edible today.', author: 'Fact' },
  { text: 'Octopuses have three hearts and blue blood.', author: 'Fact' },
  { text: 'A group of flamingos is called a flamboyance.', author: 'Fact' },
  { text: 'Bananas are berries, but strawberries are not.', author: 'Fact' },
  { text: 'The shortest war in history lasted only thirty eight minutes.', author: 'Fact' },
  { text: 'Sharks existed before trees did.', author: 'Fact' },
  { text: 'A day on Venus is longer than a year on Venus.', author: 'Fact' },
  { text: 'The human nose can detect over one trillion distinct scents.', author: 'Fact' },
  { text: 'Wombat droppings are cube shaped.', author: 'Fact' },
  { text: 'The Eiffel Tower can grow six inches taller during the summer.', author: 'Fact' },
  { text: 'Cleopatra lived closer in time to the moon landing than to the pyramids.', author: 'Fact' },
  { text: 'There are more possible chess games than atoms in the observable universe.', author: 'Fact' },
  { text: 'Sea otters hold hands while sleeping so they do not drift apart.', author: 'Fact' },
  { text: 'The dot over a lowercase letter i is called a tittle.', author: 'Fact' },
  { text: 'Scotland national animal is the unicorn.', author: 'Fact' },
  { text: 'A bolt of lightning is five times hotter than the surface of the sun.', author: 'Fact' },
  { text: 'Butterflies taste with their feet.', author: 'Fact' },
  { text: 'The first computer programmer was a woman named Ada Lovelace.', author: 'Fact' },
  { text: 'Oxford University is older than the Aztec Empire.', author: 'Fact' },
  { text: 'A single strand of spider silk is stronger than steel of the same width.', author: 'Fact' },
  { text: 'Hot water can freeze faster than cold water under the right conditions.', author: 'Fact' },
  { text: 'Cows have best friends and get stressed when they are separated.', author: 'Fact' },
  { text: 'The moon is slowly drifting away from Earth every single year.', author: 'Fact' },
  { text: 'Penguins propose to their mates with a carefully chosen pebble.', author: 'Fact' },
  { text: 'Bubble wrap was originally invented as textured wallpaper.', author: 'Fact' },
  { text: 'The inventor of the frisbee was turned into a frisbee after he died.', author: 'Fact' },
  { text: 'There is enough gold in the earth core to coat the planet knee deep.', author: 'Fact' },
  { text: 'A jiffy is an actual unit of time equal to one hundredth of a second.', author: 'Fact' },
  { text: 'Humans share about sixty percent of their DNA with bananas.', author: 'Fact' },
  { text: 'The longest word without a vowel other than y is rhythms.', author: 'Fact' },
  { text: 'Polar bears have black skin under their translucent fur.', author: 'Fact' },
  { text: 'Snails can sleep for up to three years at a time.', author: 'Fact' },
  { text: 'The unicorn was declared the national animal of Scotland in the twelfth century.', author: 'Fact' },
  { text: 'Tomatoes were once believed to be poisonous by wealthy Europeans.', author: 'Fact' },
  { text: 'An ostrich eye is bigger than its brain.', author: 'Fact' },

  // --- Proverbs and sayings ---
  { text: 'The early bird catches the worm, but the second mouse gets the cheese.', author: 'Proverb' },
  { text: 'A smooth sea never made a skilled sailor.', author: 'Proverb' },
  { text: 'Do not judge a book by its cover.', author: 'Proverb' },
  { text: 'Actions speak louder than words.', author: 'Proverb' },
  { text: 'When the wind of change blows, some build walls and others build windmills.', author: 'Chinese Proverb' },
  { text: 'A gem cannot be polished without friction.', author: 'Chinese Proverb' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'By failing to prepare, you are preparing to fail.', author: 'Benjamin Franklin' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'Either write something worth reading or do something worth writing.', author: 'Benjamin Franklin' },
  { text: 'Lost time is never found again.', author: 'Benjamin Franklin' },
  { text: 'He that can have patience can have what he will.', author: 'Benjamin Franklin' },
  { text: 'Speak softly and carry a big stick.', author: 'African Proverb' },
  { text: 'It takes a village to raise a child.', author: 'African Proverb' },
  { text: 'However long the night, the dawn will break.', author: 'African Proverb' },
  { text: 'The axe forgets, but the tree remembers.', author: 'African Proverb' },
  { text: 'Rain does not fall on one roof alone.', author: 'African Proverb' },
  { text: 'A single bracelet does not jingle.', author: 'African Proverb' },
  { text: 'Smooth roads never make good drivers.', author: 'Proverb' },
  { text: 'The nail that sticks out gets hammered down.', author: 'Japanese Proverb' },
  { text: 'Vision without action is a daydream. Action without vision is a nightmare.', author: 'Japanese Proverb' },
  { text: 'One kind word can warm three winter months.', author: 'Japanese Proverb' },
  { text: 'If you are patient in one moment of anger, you will escape a hundred days of sorrow.', author: 'Chinese Proverb' },
  { text: 'Better to light a candle than to curse the darkness.', author: 'Chinese Proverb' },
  { text: 'Teachers open the door, but you must enter by yourself.', author: 'Chinese Proverb' },
  { text: 'A book is a garden carried in the pocket.', author: 'Arabian Proverb' },
  { text: 'Ask about your neighbors before you buy the house.', author: 'Jewish Proverb' },
  { text: 'Do not be so humble, you are not that great.', author: 'Golda Meir' },
  { text: 'Trust in God, but tie your camel.', author: 'Arabian Proverb' },
  { text: 'What is done cannot be undone.', author: 'Proverb' },
  { text: 'Necessity is the mother of invention.', author: 'Proverb' },
  { text: 'Still waters run deep.', author: 'Proverb' },
  { text: 'A watched pot never boils.', author: 'Proverb' },
  { text: 'Do not put all your eggs in one basket.', author: 'Proverb' },

  // --- Music, film and the modern age ---
  { text: 'Without music, life would be a mistake.', author: 'Friedrich Nietzsche' },
  { text: 'Where words fail, music speaks.', author: 'Hans Christian Andersen' },
  { text: 'Music is the universal language of mankind.', author: 'Henry Wadsworth Longfellow' },
  { text: 'Life is what happens when you are busy making other plans.', author: 'John Lennon' },
  { text: 'You may say I am a dreamer, but I am not the only one.', author: 'John Lennon' },
  { text: 'And in the end, the love you take is equal to the love you make.', author: 'Paul McCartney' },
  { text: 'I get by with a little help from my friends.', author: 'The Beatles' },
  { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates' },
  { text: 'May the Force be with you.', author: 'Star Wars' },
  { text: 'Do or do not. There is no try.', author: 'Yoda' },
  { text: 'Fear is the path to the dark side.', author: 'Yoda' },
  { text: 'Frankly my dear, I do not give a damn.', author: 'Gone with the Wind' },
  { text: 'Here is looking at you, kid.', author: 'Casablanca' },
  { text: 'Toto, I have a feeling we are not in Kansas anymore.', author: 'The Wizard of Oz' },
  { text: 'Life is like a box of chocolates. You never know what you are going to get.', author: 'Forrest Gump' },
  { text: 'To infinity and beyond.', author: 'Buzz Lightyear' },
  { text: 'When life gets you down, you know what you got to do? Just keep swimming.', author: 'Finding Nemo' },
  { text: 'Hakuna matata means no worries for the rest of your days.', author: 'The Lion King' },
  { text: 'With great power comes great responsibility.', author: 'Spider-Man' },
  { text: 'You either die a hero or you live long enough to see yourself become the villain.', author: 'The Dark Knight' },
  { text: 'Houston, we have a problem.', author: 'Apollo 13' },
  { text: 'That is one small step for man, one giant leap for mankind.', author: 'Neil Armstrong' },
  { text: 'We choose to go to the moon not because it is easy, but because it is hard.', author: 'John F Kennedy' },
  { text: 'The truth is out there.', author: 'The X-Files' },
  { text: 'A mind needs books as a sword needs a whetstone, if it is to keep its edge.', author: 'Game of Thrones' },
  { text: 'I am going to make him an offer he cannot refuse.', author: 'The Godfather' },
  { text: 'Elementary, my dear Watson.', author: 'Sherlock Holmes' },
  { text: 'When you have eliminated the impossible, whatever remains must be the truth.', author: 'Sherlock Holmes' },
  { text: 'You see, but you do not observe.', author: 'Sherlock Holmes' },
  { text: 'It is a capital mistake to theorize before one has data.', author: 'Sherlock Holmes' },

  // --- Longer passages, for the hard tier ---
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'Success is not how high you have climbed, but how you make a positive difference to the world.', author: 'Roy T Bennett' },
  { text: 'Twenty years from now you will be more disappointed by the things you did not do than by the ones you did.', author: 'Mark Twain' },
  { text: 'The pessimist complains about the wind, the optimist expects it to change, the realist adjusts the sails.', author: 'William Arthur Ward' },
  { text: 'Courage is not the absence of fear, but rather the judgment that something else is more important than fear.', author: 'Ambrose Redmoon' },
  { text: 'A person who never made a mistake never tried anything new, and a life without error is a life without risk.', author: 'Anonymous' },
  { text: 'Education is not the filling of a pail, but the lighting of a fire that burns for the rest of a lifetime.', author: 'William Butler Yeats' },
  { text: 'The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', author: 'Isaac Asimov' },
  { text: 'Your assumptions are your windows on the world. Scrub them off every once in a while or the light will not come in.', author: 'Isaac Asimov' },
  { text: 'People will forget what you said, people will forget what you did, but they will never forget how you made them feel.', author: 'Maya Angelou' },
  { text: 'If you want to know what a man is like, take a good look at how he treats his inferiors, not his equals.', author: 'J K Rowling' },
  { text: 'It is not our abilities that show what we truly are, it is the choices we make when no one is watching us.', author: 'Anonymous' },
  { text: 'Somewhere something incredible is waiting to be known, and the universe is under no obligation to make sense to you.', author: 'Carl Sagan' },
  { text: 'The cure for boredom is curiosity, and there is no known cure for curiosity once it has taken proper hold of you.', author: 'Dorothy Parker' },
  { text: 'Do not judge each day by the harvest you reap, but rather by the seeds that you plant along the way.', author: 'Robert Louis Stevenson' },
  { text: 'Never doubt that a small group of thoughtful citizens can change the world, indeed it is the only thing that ever has.', author: 'Margaret Mead' },
  { text: 'The difference between a successful person and others is not a lack of strength but rather a lack of will.', author: 'Vince Lombardi' },
  { text: 'Perfection is not attainable, but if we chase perfection we can catch excellence somewhere along the way.', author: 'Vince Lombardi' },
  { text: 'We are all faced with a series of great opportunities brilliantly disguised as impossible situations.', author: 'Chuck Swindoll' },
  { text: 'Everybody is a genius, but if you judge a fish by its ability to climb a tree it will live believing it is stupid.', author: 'Albert Einstein' },
  { text: 'The greatest weapon against stress is our ability to choose one thought over another and hold it there.', author: 'William James' },
  { text: 'Act as if what you do makes a difference, because in ways you may never fully measure, it absolutely does.', author: 'William James' },
  { text: 'Happiness is not something ready made. It comes from your own actions and the way you meet each ordinary day.', author: 'Dalai Lama' },
  { text: 'Remember that sometimes not getting what you want is a wonderful and quite unexpected stroke of good luck.', author: 'Dalai Lama' },
  { text: 'In the end, we will remember not the words of our enemies, but the silence of our friends who said nothing.', author: 'Martin Luther King Jr' },
  { text: 'The measure of intelligence is the ability to change, and the measure of wisdom is knowing when you should.', author: 'Anonymous' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them in the first place.', author: 'Albert Einstein' },
  { text: 'A good traveler has no fixed plans and is not intent on arriving at any particular place at all.', author: 'Lao Tzu' },
  { text: 'To handle yourself use your head, but whenever you must handle other people be sure to use your heart.', author: 'Eleanor Roosevelt' },
  { text: 'The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.', author: 'Helen Keller' },
  { text: 'Optimism is the faith that leads to achievement, for nothing can be done without hope and confidence.', author: 'Helen Keller' },
  { text: 'Alone we can do so little, together we can do so much, and no worthwhile thing is ever built by one pair of hands.', author: 'Helen Keller' },
  { text: 'Keep your face always toward the sunshine and the shadows will fall away somewhere behind you.', author: 'Walt Whitman' },
  { text: 'Be curious, not judgmental, because every person you meet is fighting a battle you know nothing about.', author: 'Anonymous' },
  { text: 'The two hardest things to say in life are hello for the first time and goodbye for the last.', author: 'Moira Rogers' },
];

/**
 * Development aid: reports quotes that break the house rules. Called from
 * main.js only when running on localhost, so it never costs anything in
 * production. Returns the list of problems rather than throwing, because one
 * bad quote should never stop the game from loading.
 * @param {Array<{text: string, author: string}>} quotes
 * @returns {string[]}
 */
export function validateQuotes(quotes = QUOTES) {
  const problems = [];
  const seen = new Set();

  quotes.forEach((quote, i) => {
    const label = `#${i} "${quote.text.slice(0, 40)}..."`;

    if (!quote.text || !quote.author) {
      problems.push(`${label}: missing text or author`);
      return;
    }
    // eslint-disable-next-line no-control-regex
    if (/[^\x20-\x7E]/.test(quote.text)) {
      problems.push(`${label}: contains non-ASCII characters`);
    }
    if (quote.text.length < 20) {
      problems.push(`${label}: too short (${quote.text.length} chars)`);
    }
    if (quote.text.length > 160) {
      problems.push(`${label}: too long (${quote.text.length} chars)`);
    }
    if (!/[A-Za-z]/.test(quote.text)) {
      problems.push(`${label}: no letters to encrypt`);
    }

    const key = quote.text.toLowerCase().replace(/[^a-z]/g, '');
    if (seen.has(key)) problems.push(`${label}: duplicate`);
    seen.add(key);
  });

  return problems;
}

/**
 * Quotes filtered to a difficulty band. Length is the main lever on how long a
 * puzzle takes, so each tier gets its own slice of the pack.
 * @param {'easy'|'medium'|'hard'} difficulty
 * @returns {Array<{text: string, author: string}>}
 */
export function quotesForDifficulty(difficulty) {
  const bands = {
    easy: [20, 70],
    medium: [50, 110],
    hard: [80, 200],
  };
  const [min, max] = bands[difficulty] ?? bands.medium;
  const pool = QUOTES.filter((q) => q.text.length >= min && q.text.length <= max);
  // Never hand back an empty pool: a narrow band on a small pack would
  // otherwise make the game unplayable at that difficulty.
  return pool.length >= 10 ? pool : QUOTES;
}
